//
//  EmojiStore.swift
//  emojiTool
//
//  Created by Reona Monga on 2026/03/29.
//


import Foundation
import Combine

final class EmojiStore: ObservableObject {
    static let shared = EmojiStore()
    
    @Published private(set) var allEmojis: [EmojiEntry] = []
    private let frequencyKey      = "fm_emojiFrequency"
    private let customKeywordsKey = "fm_customKeywords"

    // Japanese lookup: emoji character → (shortName, keywords from CLDR)
    // Populated from emoji_ja.json at init time; used only in the JP search path.
    private var jaLookup: [String: JaEntry] = [:]

    // Culturally meaningful Japanese aliases not covered by CLDR.
    // These include internet slang, colloquial reading variants, and nuances
    // that Japanese speakers actually use when thinking of an emoji.
    private let jaHandBuiltAliases: [String: [String]] = [
        // ── Internet / SNS slang ──────────────────────────────────────────
        "🔥": ["やばい", "熱い", "エモい", "バズ", "バズる", "トレンド", "炎上", "激熱"],
        "😂": ["爆笑", "ウケる", "ワロタ", "笑った", "めちゃ笑える", "うける", "草"],
        "💀": ["草", "草生える", "ウケ死ぬ", "やばすぎ", "しぬ", "死ぬほど笑える"],
        "🌿": ["草", "草はえる"],
        "😭": ["号泣", "泣ける", "感動", "つらい", "悲しい", "泣く"],
        "🥺": ["懇願", "お願い", "目がうるうる", "かわいい", "懇願顔"],
        "🤔": ["うーん", "考え中", "どうかな", "検討中", "迷ってる"],
        "😤": ["ドヤ顔", "ドヤ", "得意げ", "自慢"],
        "🙄": ["呆れ", "あきれた", "はぁ", "やれやれ"],
        "😏": ["ニヤリ", "したり顔", "余裕"],
        "🥳": ["おめでとう", "祝い", "パーティー", "誕生日", "お祝い"],
        "🎉": ["おめでとう", "祝", "パーティー", "万歳", "やったー"],
        "👍": ["いいね", "了解", "オッケー", "賛成", "グッド", "サムズアップ"],
        "👎": ["ダメ", "反対", "よくない", "サムズダウン", "否定"],
        "🙏": ["よろしく", "お願い", "感謝", "ありがとう", "拝む", "合掌"],
        "❤️": ["愛してる", "好き", "大好き", "ラブ", "愛情"],
        "💔": ["失恋", "悲しい", "傷ついた", "ハートブレイク"],
        "✨": ["キラキラ", "素敵", "かわいい", "ぴかぴか", "輝く"],
        "💯": ["完璧", "100点", "満点", "最高", "パーフェクト"],
        "🔑": ["鍵", "キー", "ポイント", "重要"],
        "💡": ["アイデア", "ひらめき", "考え", "提案"],
        "⚡": ["電気", "速い", "雷", "エネルギー", "パワー"],
        "🎯": ["的中", "ズバリ", "目標", "ビンゴ", "ドンピシャ"],
        "🚀": ["ロケット", "爆速", "急上昇", "出発", "スタート"],
        "🌸": ["桜", "さくら", "春", "花見", "お花見"],
        "⛩️": ["神社", "鳥居", "お参り", "神様"],
        "🗻": ["富士山", "富士", "日本", "山"],
        "🍣": ["お寿司", "寿司", "スシ", "回転寿司"],
        "🍜": ["ラーメン", "らーめん"],
        "🍙": ["おにぎり", "お握り"],
        "🍱": ["お弁当", "弁当"],
        "🍵": ["お茶", "緑茶", "抹茶", "和菓子"],
        "🍶": ["お酒", "日本酒", "酒"],
        "🎋": ["七夕", "願い事", "短冊"],
        "🎍": ["お正月", "正月", "新年"],
        "🎎": ["ひな祭り", "雛人形"],
        "🎐": ["風鈴", "夏", "涼"],
        "🎑": ["お月見", "月見", "中秋"],
        "👘": ["着物", "和服", "浴衣"],
        "🏯": ["お城", "城", "武士", "侍", "サムライ"],
        "🗿": ["モアイ", "圧倒的", "強キャラ", "どっしり"],
        "👺": ["天狗", "鬼", "おに"],
        "👹": ["鬼", "おに", "節分"],
        // ── Nuanced emotion / reaction ────────────────────────────────────
        "😊": ["にっこり", "うれしい", "ほっこり", "微笑む"],
        "😇": ["天使", "無害", "清純"],
        "🤭": ["しまった", "口元", "くすくす"],
        "😴": ["眠い", "ねむい", "寝る", "おやすみ"],
        "🥵": ["あつい", "暑い", "熱い", "サウナ"],
        "🥶": ["さむい", "寒い", "凍える"],
        "😎": ["かっこいい", "クール", "余裕"],
        "🤓": ["オタク", "ガリ勉", "メガネ"],
        "🧐": ["なるほど", "検証", "じっくり"],
        "😱": ["びっくり", "驚いた", "怖い", "ホラー"],
        "🤯": ["衝撃", "びっくりした", "頭爆発", "衝撃的"],
        "😡": ["怒り", "むかつく", "頭にくる", "激怒"],
        "🤬": ["怒鳴る", "ブチギレ", "激怒", "暴言"],
        "😩": ["やだ", "もう嫌", "疲れた", "うんざり"],
        "😫": ["ぐったり", "くたびれた", "消耗"],
        "🥱": ["あくび", "つまらない", "眠い"],
        "💪": ["がんばれ", "頑張れ", "筋肉", "力強い", "ファイト"],
        "👀": ["注目", "チェック", "見てる", "気になる"],
        "🎮": ["ゲーム", "ゲーミング", "プレイ"],
        "📱": ["スマホ", "携帯", "スマートフォン"],
        "💻": ["パソコン", "PC", "ラップトップ", "プログラミング"],
    ]
    
    // MARK: - Hand-Built Overrides
    // Your personal "Smart" aliases go here.
    private let handBuiltAliases: [String: [String]] = [
        "🗿": ["tuff", "moai"],
        "😀": ["grinning", "happy", "grin", "smile"],
        "😃": ["smiley", "happy", "big smile", "joy"],
        "😄": ["smile", "happy", "laugh", "grin"],
        "😁": ["beaming", "grin", "teeth", "happy"],
        "😆": ["laughing", "lol", "haha", "xd", "funny"],
        "😅": ["sweat smile", "nervous", "phew", "awkward"],
        "🤣": ["rofl", "rolling", "lmao", "dying", "floor"],
        "😂": ["joy", "tears", "lol", "crying laughing"],
        "🙂": ["slightly smiling", "content", "fine", "ok"],
        "🙃": ["upside down", "silly", "sarcastic", "ironic"],
        "🫠": ["melting", "awkward", "uncomfortable", "dissolve"],
        "😉": ["wink", "flirt", "cheeky", "knowing"],
        "😊": ["blush", "warm", "grateful", "sweet"],
        "😇": ["innocent", "angel", "halo", "blessed"],
        "🥰": ["smiling hearts", "love", "adore", "smitten"],
        "😍": ["heart eyes", "love", "beautiful", "gorgeous"],
        "🤩": ["star struck", "amazed", "wow", "excited", "starstruck"],
        "😘": ["kissing heart", "kiss", "mwah", "love", "blow kiss"],
        "😗": ["kissing", "kiss", "peck"],
        "☺️": ["relaxed", "smile", "blush", "content"],
        "😚": ["kissing closed eyes", "kiss", "shy"],
        "😙": ["kissing smiling eyes", "kiss", "happy"],
        "🥲": ["smiling tear", "bittersweet", "proud", "happy cry"],
        "🫡": ["saluting", "salute", "respect", "roger", "aye", "sir", "ok"],
        "😋": ["yum", "tasty", "food", "delicious", "savoring"],
        "😛": ["tongue", "playful", "silly", "tease"],
        "😜": ["winking tongue", "playful", "silly", "crazy", "wild"],
        "🤪": ["zany", "crazy", "wild", "silly", "wacky"],
        "😝": ["squinting tongue", "gross", "silly", "disgusted"],
        "🤑": ["money mouth", "rich", "dollar", "greedy"],
        "🤗": ["hugging", "hug", "embrace", "warm"],
        "🫗": ["pouring", "tipping", "spill", "pour"],
        "🤭": ["hand over mouth", "oops", "giggle", "secret"],
        "🫢": ["open mouth gasp", "shocked", "gasp", "surprised"],
        "🫣": ["peeking", "peek", "shy", "hide", "nervous"],
        "🤫": ["shushing", "shh", "quiet", "secret", "hush"],
        "🤔": ["thinking", "hmm", "ponder", "wonder", "consider"],
        "🫤": ["diagonal mouth", "unsure", "meh", "ambiguous"],
        "🤐": ["zipper mouth", "shh", "quiet", "silence", "secret"],
        "🤨": ["raised eyebrow", "skeptical", "suspicious", "doubt"],
        "😐": ["neutral", "blank", "expressionless", "whatever"],
        "😑": ["expressionless", "blank", "done", "deadpan"],
        "😶": ["no mouth", "silent", "speechless", "mute"],
        "🫥": ["dotted line face", "invisible", "hidden", "ghost"],
        "😏": ["smirk", "smug", "sly", "mischief", "knowing"],
        "😒": ["unamused", "meh", "unimpressed", "whatever"],
        "🙄": ["eye roll", "whatever", "ugh", "sigh", "rolling"],
        "😬": ["grimacing", "nervous", "awkward", "cringe"],
        "🫨": ["shaking", "trembling", "nervous", "shock"],
        "🤥": ["lying", "pinocchio", "liar", "fib"],
        "😌": ["relieved", "peaceful", "calm", "chill"],
        "😔": ["pensive", "sad", "down", "disappointed"],
        "😪": ["sleepy", "tired", "drowsy", "zzz"],
        "🤤": ["drooling", "yummy", "hungry", "food"],
        "😴": ["sleeping", "zzz", "sleep", "nap"],
        "😷": ["mask", "sick", "ill", "covid", "cold"],
        "🤒": ["thermometer face", "sick", "fever", "ill"],
        "🤕": ["bandage", "hurt", "injured", "ouch"],
        "🤢": ["nauseated", "sick", "gross", "disgusted", "vomit"],
        "🤮": ["vomiting", "sick", "gross", "puke"],
        "🤧": ["sneezing", "sick", "achoo", "cold", "sneeze"],
        "🥵": ["hot", "sweating", "overheated", "burning", "warm"],
        "🥶": ["cold", "freezing", "shivering", "chilly", "ice"],
        "🥴": ["woozy", "drunk", "dizzy", "tipsy"],
        "😵": ["dizzy face", "knocked out", "spiral", "confused"],
        "😵‍💫": ["spiral eyes", "dizzy", "hypnotized", "confused"],
        "🤯": ["exploding head", "mindblown", "shocked", "amazed"],
        "🤠": ["cowboy", "yeehaw", "western", "hat", "country"],
        "🥳": ["party", "celebrate", "birthday", "hooray", "woo"],
        "🥸": ["disguised", "incognito", "glasses", "spy", "fake"],
        "😎": ["cool", "sunglasses", "awesome", "chill", "swag"],
        "🤓": ["nerd", "geek", "glasses", "smart", "studious"],
        "🧐": ["monocle", "scrutinize", "inspect", "fancy", "hmm"],
        "😕": ["confused", "unsure", "puzzled", "huh"],
        "😟": ["worried", "concerned", "troubled", "anxious"],
        "🙁": ["frowning", "unhappy", "sad", "disappointed"],
        "☹️": ["frown", "sad", "unhappy", "disappointed"],
        "😮": ["open mouth", "surprised", "shocked", "wow", "oh"],
        "😯": ["hushed", "surprised", "shocked", "silent"],
        "😲": ["astonished", "shocked", "amazed", "wow"],
        "😳": ["flushed", "embarrassed", "shocked", "surprised", "red"],
        "🥺": ["pleading", "puppy eyes", "begging", "sad", "please"],
        "🥹": ["holding back tears", "moved", "touched", "emotional"],
        "😦": ["frowning open", "sad", "shocked", "worried"],
        "😧": ["anguished", "pain", "suffering", "worried"],
        "😨": ["fearful", "scared", "anxious", "worried", "fear"],
        "😰": ["anxious sweat", "nervous", "worried", "sweating"],
        "😥": ["sad relieved", "disappointed", "phew", "bittersweet"],
        "😢": ["cry", "sad", "tear", "upset", "weep"],
        "😭": ["cooked", "sob", "crying", "bawling", "sad", "weeping"],
        "😱": ["scream", "shocked", "scared", "fear", "omg", "horror"],
        "😖": ["confounded", "frustrated", "confused", "distressed"],
        "😣": ["persevering", "struggling", "trying", "effort"],
        "😞": ["disappointed", "sad", "let down", "unhappy"],
        "😓": ["downcast sweat", "hard", "struggling", "effort"],
        "😩": ["weary", "tired", "exhausted", "fed up"],
        "😫": ["tired", "exhausted", "weary", "done"],
        "🥱": ["yawning", "bored", "tired", "sleepy"],
        "😤": ["steam", "huffing", "annoyed", "frustrated", "triumph"],
        "😡": ["rage", "furious", "angry", "red", "mad", "pouting"],
        "😠": ["angry", "mad", "upset", "grumpy", "mean"],
        "🤬": ["cursing", "swearing", "angry", "symbols", "mad"],
        "😈": ["smiling devil", "evil", "mischief", "villain", "purple"],
        "👿": ["angry devil", "evil", "purple devil", "demon"],
        "💀": ["cooked", "skull", "dead", "death", "bones", "spooky", "skeleton"],
        "☠️": ["skull crossbones", "poison", "danger", "death", "pirate"],
        "💩": ["poop", "poo", "crap", "funny", "hankey"],
        "🤡": ["clown", "joker", "silly", "circus", "creepy"],
        "👹": ["ogre", "monster", "demon", "scary", "japanese"],
        "👺": ["goblin", "monster", "red", "devil", "japanese"],
        "👻": ["ghost", "spooky", "boo", "halloween", "invisible"],
        "👽": ["alien", "ufo", "space", "extraterrestrial", "martian"],
        "👾": ["space invader", "game", "alien", "pixel", "arcade"],
        "🤖": ["robot", "bot", "ai", "tech", "android", "machine"],
        "😺": ["grinning cat", "cat", "happy", "smiling"],
        "😸": ["grinning cat tears", "cat", "laughing", "joy"],
        "😹": ["cat tears joy", "cat", "lol", "laughing"],
        "😻": ["heart eyes cat", "cat", "love", "adore"],
        "😼": ["smirking cat", "cat", "smug", "sly"],
        "😽": ["kissing cat", "cat", "kiss", "love"],
        "🙀": ["weary cat", "cat", "shocked", "scared", "omg"],
        "😿": ["crying cat", "cat", "sad", "tear"],
        "😾": ["pouting cat", "cat", "angry", "grumpy"],
        "👋": ["wave", "hello", "hi", "bye", "waving", "hand"],
        "🤚": ["raised back hand", "stop", "halt", "hand"],
        "🖐️": ["hand fingers splayed", "stop", "high five", "hand"],
        "✋": ["raised hand", "stop", "high five", "halt"],
        "🖖": ["vulcan salute", "spock", "star trek", "live long"],
        "🫱": ["rightwards hand", "hand", "right"],
        "🫲": ["leftwards hand", "hand", "left"],
        "🫳": ["palm down", "hand", "dismiss", "wave"],
        "🫴": ["palm up", "hand", "offer", "receive"],
        "👌": ["ok", "perfect", "okay", "chef", "zero", "good"],
        "🤌": ["pinched fingers", "italian", "chef kiss", "emphasis"],
        "🤏": ["pinching", "small", "tiny", "little", "bit"],
        "✌️": ["peace", "victory", "v", "two", "fingers"],
        "🤞": ["crossed fingers", "luck", "hope", "fingers", "wish"],
        "🫰": ["hand with index finger and thumb crossed", "snap", "money", "love"],
        "🤟": ["love you gesture", "ily", "love", "rock"],
        "🤘": ["sign of horns", "rock", "metal", "devil", "horns"],
        "🤙": ["call me", "hang loose", "shaka", "phone", "call"],
        "👈": ["point left", "left", "direction", "here"],
        "👉": ["point right", "right", "direction", "this", "here"],
        "👆": ["point up", "up", "above", "one"],
        "🖕": ["middle finger", "flip off", "rude", "offensive"],
        "👇": ["point down", "down", "below", "here"],
        "☝️": ["index pointing up", "one", "number one", "wait"],
        "🫵": ["point at viewer", "you", "pointing", "accusatory"],
        "👍": ["thumbsup", "like", "good", "approve", "yes", "ok"],
        "👎": ["thumbsdown", "dislike", "bad", "no", "disapprove"],
        "✊": ["raised fist", "power", "punch", "resist", "solidarity"],
        "👊": ["oncoming fist", "punch", "fist", "hit"],
        "🤛": ["left facing fist", "fist bump", "left"],
        "🤜": ["right facing fist", "fist bump", "right"],
        "👏": ["clap", "applause", "bravo", "clapping", "praise"],
        "🙌": ["raised hands", "celebrate", "hooray", "praise", "yay"],
        "🫶": ["heart hands", "love", "care", "hug", "adore"],
        "👐": ["open hands", "hug", "open", "embrace"],
        "🤲": ["palms up", "pray", "offer", "cup", "receive"],
        "🤝": ["handshake", "deal", "agreement", "shake", "partner"],
        "🙏": ["folded hands", "pray", "please", "thanks", "namaste", "hope"],
        "✍️": ["writing", "write", "pen", "sign", "author"],
        "💅": ["nail polish", "manicure", "nails", "fancy", "salon"],
        "🤳": ["selfie", "photo", "phone", "camera", "pic"],
        "💪": ["muscle", "strong", "flex", "power", "bicep", "strength"],
        "🦾": ["mechanical arm", "robot", "prosthetic", "cyborg", "strong"],
        "🦿": ["mechanical leg", "robot", "prosthetic", "cyborg"],
        "🦵": ["leg", "kick", "limb", "body"],
        "🦶": ["foot", "kick", "stomp", "body"],
        "👂": ["ear", "listen", "hear", "hearing"],
        "🦻": ["ear with hearing aid", "deaf", "hearing", "aid"],
        "👃": ["nose", "smell", "sniff", "body"],
        "🫀": ["anatomical heart", "heart", "organ", "body", "medical"],
        "🫁": ["lungs", "breathing", "organ", "body", "medical"],
        "🧠": ["brain", "smart", "think", "mind", "genius", "intelligent"],
        "🦷": ["tooth", "dental", "teeth", "dentist"],
        "🦴": ["bone", "skeleton", "anatomy", "body"],
        "👀": ["eyes", "look", "see", "watching", "reading", "stare"],
        "👁️": ["eye", "look", "see", "watch", "stare"],
        "👅": ["tongue", "taste", "lick", "mouth"],
        "👄": ["lips", "kiss", "mouth", "red", "lipstick"],
        "🫦": ["biting lip", "nervous", "seductive", "anxious"],
        "🧑": ["person", "human", "adult", "neutral"],
        "👦": ["boy", "kid", "child", "young", "male"],
        "👧": ["girl", "kid", "child", "young", "female"],
        "🧒": ["child", "kid", "young", "neutral"],
        "👨": ["man", "male", "adult", "person", "guy", "dude"],
        "👩": ["woman", "female", "adult", "person", "lady", "girl"],
        "🧓": ["older adult", "elderly", "senior", "neutral"],
        "👴": ["old man", "elderly", "senior", "grandfather", "grandpa"],
        "👵": ["old woman", "elderly", "senior", "grandmother", "grandma"],
        "🧑‍⚕️": ["health worker", "doctor", "nurse", "medical"],
        "👨‍⚕️": ["man health worker", "doctor", "nurse", "medical", "man"],
        "👩‍⚕️": ["woman health worker", "doctor", "nurse", "medical", "woman"],
        "🧑‍🎓": ["student", "graduate", "education", "school", "learn"],
        "👨‍🎓": ["man student", "graduate", "education", "school"],
        "👩‍🎓": ["woman student", "graduate", "education", "school"],
        "🧑‍🏫": ["teacher", "professor", "education", "school", "teach"],
        "🧑‍💻": ["technologist", "coder", "programmer", "developer", "hacker"],
        "👨‍💻": ["man technologist", "coder", "programmer", "developer"],
        "👩‍💻": ["woman technologist", "coder", "programmer", "developer"],
        "🧑‍🎨": ["artist", "painter", "creative", "art"],
        "🧑‍🚀": ["astronaut", "space", "rocket", "nasa"],
        "👮": ["police", "cop", "officer", "law", "security"],
        "🕵️": ["detective", "spy", "investigator", "sleuth", "sherlock"],
        "💂": ["guard", "soldier", "royal", "british", "london"],
        "🧑‍🍳": ["cook", "chef", "cooking", "kitchen", "food"],
        "🧑‍🌾": ["farmer", "agriculture", "plant", "harvest", "rural"],
        "🧑‍🔧": ["mechanic", "fix", "repair", "tool", "wrench"],
        "🧑‍🏭": ["factory worker", "industry", "manufacturing", "work"],
        "🧑‍💼": ["office worker", "business", "professional", "work", "suit"],
        "🧑‍🔬": ["scientist", "lab", "research", "experiment", "science"],
        "🧑‍🎤": ["singer", "music", "rock", "star", "performer"],
        "🧑‍✈️": ["pilot", "airplane", "flight", "aviation"],
        "🧑‍🚒": ["firefighter", "fire", "rescue", "hero", "emergency"],
        "🤱": ["breastfeeding", "nursing", "baby", "mother", "infant"],
        "🧑‍🍼": ["person feeding baby", "parent", "infant", "bottle", "baby"],
        "🧙": ["mage", "wizard", "witch", "magic", "sorcerer", "fantasy"],
        "🧚": ["fairy", "magic", "wings", "fantasy", "tinker"],
        "🧛": ["vampire", "dracula", "blood", "horror", "halloween"],
        "🧜": ["merperson", "mermaid", "ocean", "fantasy", "fish"],
        "🧝": ["elf", "fantasy", "tolkien", "magic", "forest"],
        "🧞": ["genie", "wish", "lamp", "magic", "disney"],
        "🧟": ["zombie", "undead", "horror", "walking dead", "brain"],
        "🧌": ["troll", "monster", "fantasy", "ugly", "internet"],
        "💆": ["massage", "relax", "spa", "head", "face"],
        "💇": ["haircut", "barber", "salon", "beauty", "hair"],
        "🚶": ["walking", "walk", "stroll", "pedestrian", "person"],
        "🧍": ["standing", "stand", "upright", "person"],
        "🧎": ["kneeling", "kneel", "pray", "bow", "person"],
        "🏃": ["running", "run", "sprint", "fast", "jog", "exercise"],
        "💃": ["woman dancing", "dance", "party", "disco", "salsa"],
        "🕺": ["man dancing", "dance", "party", "disco", "move"],
        "🕴️": ["person in suit levitating", "business", "levitate", "float"],
        "👯": ["people with bunny ears", "party", "costume", "showgirl"],
        "🧖": ["person in steamy room", "sauna", "steam", "spa", "relax"],
        "🧗": ["climbing", "rock", "climb", "sport", "bouldering"],
        "🤸": ["cartwheeling", "gymnastics", "flexible", "sport", "tumble"],
        "⛹️": ["bouncing ball", "basketball", "sport", "player"],
        "🏋️": ["weight lifting", "gym", "strong", "workout", "lift"],
        "🚴": ["cycling", "bike", "bicycle", "sport", "pedal"],
        "🏄": ["surfing", "surf", "wave", "beach", "sport"],
        "🏊": ["swimming", "swim", "pool", "water", "sport"],
        "🤽": ["water polo", "sport", "pool", "swimming"],
        "🚣": ["rowing", "boat", "canoe", "sport", "water"],
        "🧘": ["lotus", "meditation", "yoga", "calm", "relax", "zen"],
        "🏇": ["horse racing", "jockey", "equestrian", "sport", "horse"],
        "🏂": ["snowboarder", "snowboard", "ski", "winter", "sport"],
        "🪂": ["parachute", "skydive", "jump", "fall", "fly"],
        "🤼": ["wrestling", "fight", "sport", "grapple"],
        "🤺": ["fencing", "sword", "sport", "duel"],
        "🥊": ["boxing glove", "boxing", "fight", "punch", "sport"],
        "🥋": ["martial arts", "karate", "taekwondo", "judo", "fight"],
        "🎽": ["running shirt", "sport", "jersey", "athletic"],
        "🛹": ["skateboard", "skate", "cool", "tony hawk", "sport"],
        "🛼": ["roller skate", "skate", "retro", "wheels", "sport"],
        "🛷": ["sled", "sledge", "winter", "snow", "christmas"],
        "⛸️": ["ice skate", "skating", "winter", "sport", "ice"],
        "🥅": ["goal net", "hockey", "soccer", "sport", "goal"],
        "🎿": ["skis", "skiing", "winter", "sport", "snow"],
        "🛻": ["pickup truck", "truck", "vehicle", "car", "drive"],
        "🏹": ["bow and arrow", "archery", "arrow", "shoot", "hunt"],
        "🎣": ["fishing", "fish", "rod", "pole", "angler", "catch"],
        "🤿": ["diving", "scuba", "snorkel", "underwater", "ocean"],
        "🥌": ["curling stone", "curling", "sport", "winter", "ice"],
        "🐶": ["dog", "puppy", "pet", "woof", "doggo", "canine"],
        "🐱": ["cat", "kitty", "pet", "meow", "kitten", "feline"],
        "🐭": ["mouse", "rodent", "pet", "small", "squeak"],
        "🐹": ["hamster", "pet", "rodent", "cute", "fluffy"],
        "🐰": ["rabbit", "bunny", "hop", "easter", "cute", "fluffy"],
        "🦊": ["fox", "cunning", "orange", "sly", "clever"],
        "🐻": ["bear", "grizzly", "brown", "animal", "teddy"],
        "🐼": ["panda", "cute", "bamboo", "bear", "china"],
        "🐻‍❄️": ["polar bear", "arctic", "ice", "white", "bear", "cold"],
        "🐨": ["koala", "australia", "eucalyptus", "marsupial", "cute"],
        "🐯": ["tiger", "stripes", "fierce", "big cat", "roar"],
        "🦁": ["lion", "roar", "fierce", "king", "mane", "savanna"],
        "🐮": ["cow", "moo", "farm", "milk", "bovine"],
        "🐷": ["pig", "oink", "farm", "pork", "bacon", "pink"],
        "🐸": ["frog", "green", "toad", "ribbit", "jump", "kermit"],
        "🐵": ["monkey", "ape", "primate", "silly", "banana"],
        "🙈": ["see no evil", "monkey", "hide", "blind", "ashamed"],
        "🙉": ["hear no evil", "monkey", "deaf", "ignore", "ashamed"],
        "🙊": ["speak no evil", "monkey", "mute", "silent", "ashamed"],
        "🐔": ["chicken", "hen", "farm", "bird", "cluck", "poultry"],
        "🐧": ["penguin", "arctic", "cold", "waddle", "bird", "cute"],
        "🐦": ["bird", "tweet", "chirp", "fly", "feather"],
        "🐦‍⬛": ["black bird", "crow", "raven", "dark", "bird"],
        "🐤": ["chick", "baby", "bird", "cute", "yellow", "chirp"],
        "🦆": ["duck", "quack", "pond", "swim", "bird", "water"],
        "🦅": ["eagle", "majestic", "fly", "america", "bird", "freedom"],
        "🦉": ["owl", "wise", "night", "hoot", "bird", "knowledge"],
        "🦇": ["bat", "halloween", "night", "flying", "vampire", "cave"],
        "🐺": ["wolf", "howl", "wild", "pack", "moon", "forest"],
        "🐗": ["boar", "wild pig", "tusks", "forest", "beast"],
        "🐴": ["horse", "equine", "neigh", "gallop", "mane", "ride"],
        "🦄": ["unicorn", "magic", "rainbow", "mythical", "horn", "sparkle"],
        "🐝": ["bee", "honey", "buzz", "sting", "hive", "flower"],
        "🪱": ["worm", "soil", "garden", "crawl", "dirt", "earth"],
        "🐛": ["bug", "caterpillar", "insect", "crawl", "larva"],
        "🦋": ["butterfly", "pretty", "flutter", "transform", "colorful"],
        "🐌": ["snail", "slow", "shell", "garden", "pace"],
        "🐞": ["ladybug", "lucky", "red", "spots", "insect", "garden"],
        "🐜": ["ant", "colony", "work", "insect", "small", "strong"],
        "🪲": ["beetle", "insect", "bug", "hard", "shell"],
        "🦟": ["mosquito", "bite", "itch", "pest", "insect", "blood"],
        "🦗": ["cricket", "chirp", "insect", "night", "sound", "jump"],
        "🪳": ["cockroach", "pest", "gross", "insect", "resilient"],
        "🕷️": ["spider", "web", "crawl", "arachnid", "scary", "halloween"],
        "🦂": ["scorpion", "sting", "desert", "arachnid", "dangerous"],
        "🐢": ["turtle", "slow", "shell", "ocean", "reptile", "patient"],
        "🐍": ["snake", "hiss", "venom", "reptile", "slither", "python"],
        "🦎": ["lizard", "reptile", "gecko", "chameleon", "green", "scale"],
        "🦖": ["t rex", "dinosaur", "extinct", "jurassic", "prehistoric"],
        "🦕": ["sauropod", "dinosaur", "extinct", "long neck", "brachiosaurus"],
        "🐊": ["crocodile", "alligator", "snap", "reptile", "swamp", "teeth"],
        "🐋": ["whale", "ocean", "big", "mammal", "blue whale", "sea"],
        "🐳": ["spouting whale", "ocean", "mammal", "spout", "water", "sea"],
        "🐬": ["dolphin", "flipper", "smart", "ocean", "mammal", "swim"],
        "🦭": ["seal", "ocean", "mammal", "cute", "arctic", "flipper"],
        "🐟": ["fish", "ocean", "swim", "seafood", "scale", "catch"],
        "🐠": ["tropical fish", "colorful", "ocean", "reef", "aquarium"],
        "🐡": ["blowfish", "puffer", "ocean", "spiky", "inflate"],
        "🦈": ["shark", "dangerous", "ocean", "teeth", "bite", "jaws"],
        "🐙": ["octopus", "tentacles", "ocean", "smart", "ink", "squid"],
        "🐚": ["shell", "beach", "ocean", "spiral", "seashell"],
        "🪸": ["coral", "reef", "ocean", "colorful", "ecosystem"],
        "🦀": ["crab", "seafood", "beach", "pinch", "crustacean", "red"],
        "🦞": ["lobster", "seafood", "red", "claws", "crustacean", "ocean"],
        "🦐": ["shrimp", "seafood", "small", "pink", "crustacean"],
        "🦑": ["squid", "ocean", "tentacles", "ink", "calamari", "seafood"],
        "🦪": ["oyster", "pearl", "seafood", "ocean", "shell"],
        "🌿": ["herb", "plant", "green", "leaf", "nature", "grow"],
        "🪴": ["potted plant", "houseplant", "indoor", "nature", "grow"],
        "🌵": ["cactus", "desert", "prickly", "succulent", "dry"],
        "🎄": ["christmas tree", "xmas", "holiday", "pine", "festive"],
        "🌲": ["evergreen", "pine", "tree", "forest", "nature", "green"],
        "🌳": ["deciduous tree", "tree", "nature", "park", "leaf", "green"],
        "🌴": ["palm tree", "tropical", "beach", "vacation", "island", "coconut"],
        "🌱": ["seedling", "grow", "sprout", "plant", "new", "baby"],
        "☘️": ["shamrock", "luck", "irish", "clover", "saint patricks"],
        "🍀": ["four leaf clover", "luck", "lucky", "rare", "wish", "irish"],
        "🎋": ["tanabata tree", "bamboo", "japanese", "wish", "festival"],
        "🎍": ["pine decoration", "japanese", "new year", "pine", "bamboo"],
        "🪻": ["hyacinth", "flower", "purple", "spring", "bloom", "fragrant"],
        "🌾": ["sheaf of rice", "wheat", "harvest", "grain", "farm", "food"],
        "🍁": ["maple leaf", "canada", "autumn", "fall", "red", "orange"],
        "🍂": ["fallen leaf", "autumn", "fall", "brown", "nature", "season"],
        "🍃": ["leaf fluttering", "wind", "nature", "green", "fresh"],
        "🪺": ["nest with eggs", "bird", "spring", "hatching", "home"],
        "🪹": ["empty nest", "bird", "home", "nature", "tree"],
        "🍄": ["mushroom", "fungi", "forest", "red", "spots", "mario"],
        "🌰": ["chestnut", "autumn", "nut", "food", "tree", "roast"],
        "🪨": ["rock", "stone", "heavy", "solid", "nature", "geology"],
        "🪵": ["wood", "log", "tree", "lumber", "fire", "nature"],
        "🌊": ["wave", "ocean", "surf", "sea", "water", "beach"],
        "🌬️": ["wind", "blow", "air", "breeze", "gust", "cold"],
        "🌀": ["cyclone", "tornado", "spin", "hurricane", "dizzy", "swirl"],
        "🌈": ["rainbow", "colorful", "pride", "colors", "rain", "sun"],
        "☀️": ["sun", "sunny", "bright", "warm", "weather", "clear"],
        "🌤️": ["sun small cloud", "partly cloudy", "weather", "mostly sunny"],
        "⛅": ["sun behind cloud", "partly cloudy", "weather", "cloud"],
        "🌥️": ["sun behind large cloud", "cloudy", "overcast", "weather"],
        "☁️": ["cloud", "overcast", "weather", "grey", "sky"],
        "🌦️": ["sun behind rain cloud", "shower", "drizzle", "weather"],
        "🌧️": ["rain", "rainy", "weather", "umbrella", "wet", "cloud"],
        "⛈️": ["thunder", "storm", "lightning", "rain", "weather"],
        "🌩️": ["lightning", "storm", "thunder", "bolt", "electric"],
        "🌨️": ["snow", "snowflake", "winter", "cold", "weather"],
        "❄️": ["snowflake", "snow", "cold", "winter", "ice", "freeze"],
        "☃️": ["snowman", "winter", "christmas", "cold", "snow", "frosty"],
        "⛄": ["snowman no snow", "frosty", "winter", "cold", "christmas"],
        "🌡️": ["thermometer", "temperature", "hot", "cold", "weather", "measure"],
        "💨": ["dashing", "wind", "fast", "speed", "air", "blow"],
        "💧": ["droplet", "water", "rain", "tear", "blue", "liquid"],
        "💦": ["sweat droplets", "water", "splash", "wet", "sweat", "swim"],
        "🫧": ["bubbles", "soap", "clean", "fizz", "water", "sparkle"],
        "🌫️": ["fog", "mist", "foggy", "cloudy", "hazy", "weather"],
        "🌋": ["volcano", "eruption", "lava", "geological", "mountain", "fire"],
        "⛰️": ["mountain", "peak", "summit", "climb", "nature", "tall"],
        "🏔️": ["snow capped mountain", "alpine", "winter", "climb", "cold"],
        "🗻": ["mount fuji", "japan", "mountain", "iconic", "fuji"],
        "🏕️": ["camping", "tent", "outdoors", "nature", "campfire", "hike"],
        "🏖️": ["beach", "sand", "ocean", "vacation", "sun", "summer", "surf"],
        "🏜️": ["desert", "sand", "hot", "dry", "cactus", "arid"],
        "🏝️": ["island", "tropical", "vacation", "paradise", "beach", "palm"],
        "🏞️": ["park", "nature", "landscape", "river", "trees", "scenic"],
        "🌍": ["earth africa", "world", "globe", "europe", "africa", "planet"],
        "🌎": ["earth americas", "world", "globe", "planet", "america", "map"],
        "🌏": ["earth asia", "world", "globe", "planet", "asia", "map"],
        "🌐": ["globe", "internet", "world", "international", "network", "web"],
        "🗺️": ["map", "world", "geography", "travel", "navigation", "explore"],
        "🍇": ["grapes", "fruit", "wine", "purple", "bunch", "vineyard"],
        "🍈": ["melon", "fruit", "green", "cantaloupe", "honeydew", "sweet"],
        "🍉": ["watermelon", "fruit", "summer", "seed", "red", "green"],
        "🍊": ["tangerine", "orange", "citrus", "fruit", "vitamin c"],
        "🍋": ["lemon", "citrus", "sour", "yellow", "fruit", "tart"],
        "🍌": ["banana", "fruit", "yellow", "peel", "monkey", "slip"],
        "🍍": ["pineapple", "tropical", "fruit", "sweet", "spiky", "hawaii"],
        "🥭": ["mango", "tropical", "fruit", "yellow", "sweet", "india"],
        "🍎": ["red apple", "fruit", "teacher", "healthy", "crisp", "red"],
        "🍏": ["green apple", "fruit", "sour", "healthy", "green", "crisp"],
        "🍐": ["pear", "fruit", "green", "sweet", "juicy", "orchard"],
        "🍑": ["peach", "fruit", "pink", "sweet", "fuzzy", "summer"],
        "🍒": ["cherries", "fruit", "red", "pair", "sweet", "summer", "pie"],
        "🍓": ["strawberry", "fruit", "red", "sweet", "summer", "jam"],
        "🫐": ["blueberries", "fruit", "blue", "antioxidant", "muffin", "jam"],
        "🥝": ["kiwi", "fruit", "green", "sour", "new zealand", "tropical"],
        "🍅": ["tomato", "red", "vegetable", "salad", "sauce", "pizza"],
        "🫒": ["olive", "oil", "mediterranean", "green", "salty", "food"],
        "🥥": ["coconut", "tropical", "water", "milk", "palm", "island"],
        "🥑": ["avocado", "healthy", "green", "toast", "guacamole", "fat"],
        "🍆": ["eggplant", "purple", "vegetable", "aubergine", "brinjal"],
        "🥔": ["potato", "starchy", "vegetable", "fry", "bake", "mash"],
        "🥕": ["carrot", "orange", "vegetable", "rabbit", "healthy", "crunch"],
        "🌽": ["corn", "maize", "vegetable", "yellow", "summer", "pop"],
        "🌶️": ["hot pepper", "spicy", "red", "chili", "heat", "sauce"],
        "🫑": ["bell pepper", "capsicum", "vegetable", "green", "red", "pepper"],
        "🥒": ["cucumber", "green", "vegetable", "cool", "fresh", "salad"],
        "🥬": ["leafy greens", "vegetable", "healthy", "salad", "green", "spinach"],
        "🥦": ["broccoli", "vegetable", "healthy", "green", "tree", "nutrition"],
        "🧄": ["garlic", "pungent", "cooking", "italian", "vampire", "flavor"],
        "🧅": ["onion", "cooking", "layer", "smell", "vegetable", "savory"],
        "🥜": ["peanuts", "nuts", "salty", "snack", "butter", "legume"],
        "🫘": ["beans", "legume", "protein", "cook", "vegetable", "stew"],
        "🍞": ["bread", "loaf", "bake", "carb", "toast", "wheat"],
        "🥐": ["croissant", "french", "pastry", "breakfast", "flaky", "buttery"],
        "🥖": ["baguette", "french", "bread", "long", "bakery", "crusty"],
        "🫓": ["flatbread", "pita", "naan", "wrap", "bread", "flat"],
        "🥨": ["pretzel", "salty", "bread", "twist", "german", "snack"],
        "🥯": ["bagel", "bread", "breakfast", "new york", "cream cheese", "round"],
        "🥞": ["pancakes", "breakfast", "maple", "syrup", "fluffy", "stack"],
        "🧇": ["waffle", "breakfast", "crispy", "maple", "sweet", "belgium"],
        "🧀": ["cheese", "dairy", "yellow", "pizza", "burger", "gouda"],
        "🍖": ["meat bone", "food", "carnivore", "grill", "bbq", "protein"],
        "🍗": ["poultry leg", "chicken", "fried", "food", "kfc", "drumstick"],
        "🥩": ["cut of meat", "steak", "beef", "grill", "food", "protein"],
        "🥓": ["bacon", "breakfast", "pork", "crispy", "salty", "fry"],
        "🌭": ["hotdog", "frank", "mustard", "relish", "baseball", "food"],
        "🍔": ["hamburger", "burger", "beef", "fast food", "bun", "patty"],
        "🍟": ["fries", "french fries", "fast food", "salty", "potato", "crispy"],
        "🍕": ["pizza", "italian", "cheese", "tomato", "slice", "delivery"],
        "🫔": ["tamale", "mexican", "corn", "food", "wrap", "masa"],
        "🥪": ["sandwich", "lunch", "bread", "deli", "sub", "food"],
        "🥙": ["stuffed flatbread", "wrap", "falafel", "pita", "kebab", "food"],
        "🧆": ["falafel", "middle eastern", "fried", "chickpea", "street food"],
        "🥚": ["egg", "breakfast", "oval", "yolk", "chicken", "protein"],
        "🍳": ["frying pan", "cook", "breakfast", "egg", "kitchen", "chef"],
        "🥘": ["shallow pan", "stew", "cook", "casserole", "paella", "food"],
        "🍲": ["stew", "pot", "soup", "cook", "warm", "comfort"],
        "🫕": ["fondue", "swiss", "cheese", "dip", "pot", "melt"],
        "🥣": ["bowl with spoon", "cereal", "breakfast", "oatmeal", "porridge"],
        "🥗": ["green salad", "healthy", "fresh", "vegetable", "diet", "lunch"],
        "🍿": ["popcorn", "movie", "cinema", "salty", "snack", "butter"],
        "🧈": ["butter", "dairy", "spread", "fat", "cook", "bake"],
        "🧂": ["salt", "seasoning", "flavor", "mineral", "shake", "cook"],
        "🥫": ["canned food", "tin", "preserve", "soup", "pantry", "can"],
        "🍱": ["bento box", "japanese", "lunch", "box", "sushi", "food"],
        "🍘": ["rice cracker", "japanese", "snack", "soy", "crispy", "rice"],
        "🍙": ["rice ball", "japanese", "onigiri", "rice", "seaweed", "food"],
        "🍚": ["cooked rice", "asian", "staple", "bowl", "food", "white"],
        "🍛": ["curry", "indian", "spicy", "yellow", "rice", "sauce"],
        "🍜": ["ramen", "noodles", "soup", "japanese", "bowl", "broth"],
        "🍝": ["spaghetti", "italian", "pasta", "tomato", "meatball", "sauce"],
        "🍠": ["roasted sweet potato", "japan", "orange", "sweet", "baked"],
        "🍢": ["oden", "japanese", "stew", "skewer", "winter", "dashi"],
        "🍣": ["sushi", "japanese", "fish", "rice", "raw", "roll", "fresh"],
        "🍤": ["fried shrimp", "tempura", "seafood", "japanese", "crispy"],
        "🍥": ["fish cake", "japanese", "swirl", "naruto", "food", "pink"],
        "🥮": ["moon cake", "chinese", "mid autumn", "pastry", "festival"],
        "🍡": ["dango", "japanese", "sweet", "skewer", "pink", "dessert"],
        "🧁": ["cupcake", "sweet", "dessert", "frosting", "bake", "birthday"],
        "🍦": ["soft ice cream", "ice cream", "swirl", "vanilla", "sweet", "cone"],
        "🍧": ["shaved ice", "japanese", "sweet", "summer", "cold", "fruit"],
        "🍨": ["ice cream", "scoop", "dessert", "sweet", "cold", "vanilla"],
        "🍩": ["donut", "doughnut", "sweet", "pastry", "glazed", "ring"],
        "🍪": ["cookie", "sweet", "chocolate chip", "bake", "dessert", "treat"],
        "🎂": ["birthday cake", "celebrate", "candles", "party", "sweet", "bake"],
        "🍰": ["shortcake", "slice", "sweet", "cake", "dessert", "strawberry"],
        "🧃": ["juice box", "drink", "capri", "straw", "sweet", "fruit"],
        "🥛": ["milk", "dairy", "white", "drink", "healthy", "cow", "calcium"],
        "☕": ["coffee", "hot", "cafe", "espresso", "morning", "caffeine"],
        "🫖": ["teapot", "tea", "brew", "kettle", "hot", "steep"],
        "🍵": ["tea", "green tea", "hot", "cup", "matcha", "japanese", "calm"],
        "🧋": ["bubble tea", "boba", "taiwan", "milk tea", "pearls", "drink"],
        "🍶": ["sake", "japanese", "rice wine", "alcohol", "warm", "drink"],
        "🍾": ["champagne", "celebrate", "bubbly", "pop", "party", "wedding"],
        "🍷": ["wine", "red", "glass", "alcohol", "drink", "dinner", "grape"],
        "🍸": ["cocktail", "martini", "alcohol", "drink", "party", "gin"],
        "🍹": ["tropical drink", "cocktail", "vacation", "beach", "umbrella", "rum"],
        "🍺": ["beer", "cheers", "pint", "amber", "drink", "pub", "bar"],
        "🍻": ["clinking beers", "cheers", "celebrate", "drink", "toast", "friends"],
        "🥂": ["clinking glasses", "cheers", "champagne", "celebrate", "toast"],
        "🥃": ["tumbler", "whiskey", "scotch", "bourbon", "drink", "glass", "rocks"],
        "🧉": ["mate", "south american", "drink", "herbal", "tea", "argentina"],
        "🚗": ["car", "drive", "vehicle", "automobile", "red", "road", "commute"],
        "🚕": ["taxi", "cab", "yellow", "ride", "hail", "uber", "city"],
        "🚙": ["suv", "car", "vehicle", "drive", "road", "family"],
        "🚌": ["bus", "transit", "public", "commute", "school", "city"],
        "🚎": ["trolleybus", "bus", "electric", "transit", "city", "rail"],
        "🏎️": ["racing car", "formula1", "fast", "speed", "race", "sport"],
        "🚓": ["police car", "cop", "siren", "emergency", "law", "chase"],
        "🚑": ["ambulance", "emergency", "hospital", "medical", "siren", "rescue"],
        "🚒": ["fire truck", "firefighter", "emergency", "rescue", "red", "siren"],
        "🚐": ["minibus", "van", "transit", "shuttle", "group"],
        "🚚": ["delivery truck", "shipping", "freight", "move", "transport"],
        "🚛": ["articulated lorry", "semi", "truck", "freight", "highway", "haul"],
        "🚜": ["tractor", "farm", "agriculture", "vehicle", "field", "rural"],
        "🏍️": ["motorcycle", "moped", "bike", "ride", "fast", "vroom"],
        "🛵": ["scooter", "moped", "vespa", "ride", "city", "commute"],
        "🛺": ["auto rickshaw", "tuk tuk", "india", "transport", "three wheel"],
        "🚲": ["bicycle", "bike", "pedal", "cycle", "eco", "sport", "ride"],
        "🛴": ["kick scooter", "scooter", "ride", "urban", "commute", "electric"],
        "🚏": ["bus stop", "transit", "sign", "wait", "commute", "public"],
        "🛣️": ["motorway", "highway", "road", "drive", "trip"],
        "🛤️": ["railway track", "train", "rail", "tracks", "metro"],
        "⛽": ["fuel pump", "gas", "petrol", "station", "car", "refill"],
        "🚧": ["construction", "barrier", "warning", "road", "work"],
        "⚓": ["anchor", "ship", "sail", "ocean", "dock", "boat"],
        "🛟": ["lifebuoy", "ring", "safety", "ocean", "rescue", "boat"],
        "⛵": ["sailboat", "sail", "wind", "ocean", "boat", "marina"],
        "🚤": ["speedboat", "fast", "water", "boat", "wave", "motor"],
        "🛥️": ["motor boat", "water", "boat", "cruise", "motor", "wave"],
        "🛳️": ["passenger ship", "cruise", "ocean", "liner", "ship", "travel"],
        "⛴️": ["ferry", "boat", "water", "transport", "travel", "cross"],
        "🚢": ["ship", "ocean", "cruise", "travel", "large", "liner"],
        "✈️": ["airplane", "plane", "fly", "travel", "flight", "airport", "jet"],
        "🛩️": ["small plane", "fly", "aviation", "prop", "travel", "private"],
        "🛫": ["departure", "takeoff", "fly", "airport", "travel", "up"],
        "🛬": ["landing", "arrival", "fly", "airport", "travel", "down"],
        "🛪": ["flying saucer", "ufo", "alien", "space", "sci fi", "hover"],
        "💺": ["seat", "chair", "airplane", "sit", "class", "buckle"],
        "🚁": ["helicopter", "fly", "rotor", "emergency", "tour", "military"],
        "🚟": ["suspension railway", "monorail", "train", "futuristic", "rail"],
        "🚠": ["mountain cableway", "gondola", "cable", "ski", "mountain", "lift"],
        "🚡": ["aerial tramway", "cable car", "mountain", "gondola", "sky"],
        "🛰️": ["satellite", "space", "orbit", "communication", "nasa", "tech"],
        "🚀": ["rocket", "launch", "fast", "space", "nasa", "ship", "blast"],
        "🛸": ["flying saucer", "ufo", "alien", "space", "sci fi", "future"],
        "🚂": ["steam locomotive", "train", "old", "rail", "choo choo", "vintage"],
        "🚃": ["railway car", "train", "car", "transit", "rail", "commute"],
        "🚄": ["high speed train", "bullet", "shinkansen", "fast", "rail", "japan"],
        "🚅": ["bullet train", "shinkansen", "japan", "fast", "rail", "speed"],
        "🚆": ["train", "rail", "transit", "commute", "travel"],
        "🚇": ["metro", "subway", "underground", "transit", "tube", "city"],
        "🚈": ["light rail", "transit", "train", "commute", "electric", "rail"],
        "🚉": ["station", "train", "transit", "commute", "stop", "rail"],
        "🚊": ["tram", "transit", "rail", "street", "city", "electric"],
        "🚝": ["monorail", "futuristic", "transit", "single rail", "train"],
        "🚞": ["mountain railway", "scenic", "swiss", "cog", "steep", "rail"],
        "🚋": ["tram car", "street", "transit", "city", "electric", "rail"],
        "🧭": ["compass", "navigate", "direction", "north", "explore", "hike"],
        "🏟️": ["stadium", "sports", "arena", "crowd", "game", "event", "concert"],
        "🏛️": ["classical building", "museum", "government", "columns", "history"],
        "🏗️": ["building construction", "crane", "build", "work", "develop"],
        "🧱": ["brick", "wall", "build", "solid", "red", "block"],
        "🛖": ["hut", "cabin", "primitive", "village", "thatched", "simple"],
        "🏘️": ["houses", "neighborhood", "residential", "suburb", "home"],
        "🏚️": ["derelict house", "abandoned", "ruined", "empty", "ghost", "old"],
        "🏠": ["house", "home", "building", "residence", "live", "family"],
        "🏡": ["house garden", "home", "garden", "suburban", "family", "yard"],
        "🏢": ["office building", "work", "business", "corporate", "skyscraper"],
        "🏣": ["japanese post office", "mail", "japan", "post", "office"],
        "🏤": ["post office", "mail", "envelope", "send", "government", "europe"],
        "🏥": ["hospital", "medical", "health", "emergency", "doctor", "sick"],
        "🏦": ["bank", "money", "finance", "atm", "savings", "deposit"],
        "🏧": ["atm", "cash", "money", "bank", "withdraw", "machine"],
        "🏨": ["hotel", "room", "travel", "stay", "lodging", "accommodation"],
        "🏩": ["love hotel", "japan", "pink", "lodging", "romantic", "couple"],
        "🏪": ["convenience store", "shop", "night", "open", "snack", "24h"],
        "🏫": ["school", "education", "learn", "study", "kids", "building"],
        "🏬": ["department store", "mall", "shop", "retail", "buy", "floor"],
        "🏭": ["factory", "industrial", "manufacture", "work", "chimney", "produce"],
        "🏯": ["japanese castle", "feudal", "samurai", "japan", "historic", "tower"],
        "🏰": ["castle", "medieval", "europe", "historic", "princess", "king"],
        "💒": ["wedding", "chapel", "church", "marry", "love", "ceremony"],
        "🗼": ["eiffel tower", "paris", "france", "iconic", "landmark", "travel"],
        "🗽": ["statue of liberty", "nyc", "america", "freedom", "landmark", "new york"],
        "⛪": ["church", "worship", "christian", "religion", "pray", "cross"],
        "🕌": ["mosque", "islam", "muslim", "worship", "minaret", "religion"],
        "🛕": ["hindu temple", "worship", "india", "religion", "mandir", "pray"],
        "🕍": ["synagogue", "jewish", "worship", "star of david", "religion"],
        "⛩️": ["shinto shrine", "japan", "torii", "religion", "gate", "worship"],
        "🕋": ["kaaba", "islam", "mecca", "hajj", "worship", "cube", "religion"],
        "⛲": ["fountain", "water", "park", "plaza", "spray", "garden"],
        "⛺": ["tent", "camping", "outdoors", "shelter", "nature", "sleep"],
        "🌁": ["foggy", "mist", "city", "bridge", "atmosphere", "weather"],
        "🌃": ["night with stars", "city", "night", "star", "sky", "glow"],
        "🌄": ["sunrise mountain", "dawn", "morning", "sun", "mountain", "peak"],
        "🌅": ["sunrise", "dawn", "morning", "horizon", "orange", "sun", "beach"],
        "🌆": ["city sunset", "buildings", "dusk", "evening", "urban", "golden"],
        "🌇": ["city sunrise", "buildings", "dawn", "morning", "urban", "orange"],
        "🌉": ["bridge night", "city", "lights", "suspension", "night", "river"],
        "🌌": ["milky way", "galaxy", "space", "star", "night", "astronomy"],
        "🌠": ["shooting star", "wish", "night", "sky", "meteor", "falling"],
        "🎆": ["fireworks", "celebrate", "new year", "bang", "colorful", "sky"],
        "🎇": ["sparkler", "celebrate", "new year", "shimmer", "light", "fire"],
        "🎃": ["jack o lantern", "halloween", "pumpkin", "october", "scary", "orange"],
        "🧨": ["firecracker", "chinese new year", "bang", "red", "explosive", "luck"],
        "✨": ["sparkles", "magic", "stars", "glitter", "shiny", "twinkle"],
        "🎉": ["party", "celebrate", "tada", "confetti", "woo", "hooray"],
        "🎊": ["confetti", "celebrate", "party", "colorful", "balloon", "pop"],
        "🎎": ["japanese dolls", "hina", "festival", "japan", "doll", "traditional"],
        "🎏": ["carp streamer", "japan", "koinobori", "festival", "wind", "fish"],
        "🎐": ["wind chime", "japan", "summer", "festival", "tinkle", "breeze"],
        "🎑": ["moon viewing", "japan", "tsukimi", "rabbit", "autumn", "harvest"],
        "🎗️": ["reminder ribbon", "awareness", "yellow", "cause", "support"],
        "🎟️": ["admission tickets", "event", "concert", "show", "entry", "pass"],
        "🎫": ["ticket", "event", "admission", "show", "movie", "concert"],
        "🎖️": ["military medal", "honor", "award", "service", "bravery"],
        "🏆": ["trophy", "winner", "gold", "prize", "champion", "award", "best"],
        "🥇": ["first place", "gold", "medal", "winner", "best", "champion"],
        "🥈": ["second place", "silver", "medal", "runner up"],
        "🥉": ["third place", "bronze", "medal", "podium", "third"],
        "🏅": ["sports medal", "award", "win", "achieve", "honor", "game"],
        "🎯": ["dart", "target", "bullseye", "aim", "goal", "accurate", "hit"],
        "🪀": ["yoyo", "toy", "skill", "trick", "spin", "string", "retro"],
        "🪁": ["kite", "fly", "wind", "colorful", "spring", "outdoor", "sky"],
        "🎱": ["billiards", "pool", "eight ball", "billiard", "cue", "snooker"],
        "🔮": ["crystal ball", "fortune", "predict", "magic", "mystic", "see"],
        "🪄": ["magic wand", "abracadabra", "trick", "illusion", "poof", "magic"],
        "🎮": ["video game", "gaming", "controller", "play", "console", "xbox", "ps"],
        "🕹️": ["joystick", "arcade", "game", "control", "retro", "atari"],
        "🎲": ["die", "dice", "game", "random", "chance", "board", "roll"],
        "🧩": ["puzzle", "piece", "jigsaw", "fit", "solve", "game", "brain"],
        "🧸": ["teddy bear", "toy", "soft", "cute", "plush", "cuddle", "bear"],
        "🪆": ["nesting dolls", "matryoshka", "russian", "toy", "doll", "colorful"],
        "🪅": ["pinata", "party", "candy", "mexican", "birthday", "hit", "fiesta"],
        "🖼️": ["framed picture", "art", "painting", "museum", "gallery", "wall"],
        "🎨": ["palette", "art", "paint", "creative", "design", "color", "artist"],
        "🧵": ["thread", "sew", "string", "needle", "craft", "diy", "textile"],
        "🪡": ["spool", "thread", "craft", "weave", "string", "needle"],
        "🧶": ["yarn", "knit", "craft", "wool", "cozy", "diy", "crochet"],
        "🪢": ["knot", "rope", "tie", "bow", "sailor", "craft"],
        "👓": ["glasses", "eyewear", "spectacles", "see", "vision", "smart"],
        "🕶️": ["sunglasses", "cool", "sun", "shades", "fashion", "uv"],
        "🥽": ["goggles", "protect", "safety", "lab", "swim", "eye"],
        "🌂": ["umbrella", "rain", "wet", "weather", "protect", "drizzle"],
        "☂️": ["umbrella open", "rain", "protect", "wet", "weather"],
        "👔": ["necktie", "formal", "business", "suit", "professional", "office"],
        "👕": ["tshirt", "casual", "shirt", "top", "clothing", "wear"],
        "👖": ["jeans", "denim", "pants", "casual", "blue", "wear"],
        "🧣": ["scarf", "winter", "warm", "fashion", "neck", "cozy"],
        "🧤": ["gloves", "winter", "warm", "hands", "cold", "protect"],
        "🧥": ["coat", "winter", "warm", "outer", "jacket", "fashion"],
        "🥼": ["lab coat", "doctor", "scientist", "medical", "white", "research"],
        "🦺": ["safety vest", "work", "hi vis", "construction", "reflective"],
        "👗": ["dress", "fashion", "formal", "woman", "clothing", "elegant"],
        "👘": ["kimono", "japanese", "traditional", "silk", "fashion", "ceremonial"],
        "🥻": ["sari", "indian", "traditional", "fashion", "clothing", "wrap"],
        "🩱": ["swimsuit", "swim", "beach", "summer", "one piece", "pool"],
        "🩲": ["briefs", "underwear", "swim", "beach", "clothing", "intimate"],
        "🩳": ["shorts", "summer", "casual", "beach", "pants", "clothing"],
        "👙": ["bikini", "swim", "beach", "summer", "fashion", "two piece"],
        "👚": ["woman clothes", "top", "shirt", "fashion", "clothing", "casual"],
        "👛": ["purse", "wallet", "money", "bag", "fashion", "accessory"],
        "👜": ["handbag", "purse", "fashion", "bag", "accessory", "woman"],
        "👝": ["clutch bag", "small", "fashion", "pouch", "accessory"],
        "🎒": ["backpack", "bag", "school", "travel", "hike", "carry"],
        "🧳": ["luggage", "travel", "suitcase", "trip", "pack", "airport"],
        "👒": ["hat", "straw", "sun", "fashion", "summer", "beach", "shade"],
        "🎩": ["top hat", "formal", "magic", "sir", "tuxedo", "gentleman"],
        "🧢": ["baseball cap", "cap", "hat", "casual", "sporty", "bro"],
        "⛑️": ["rescue helmet", "safety", "hard hat", "protect", "work"],
        "📿": ["prayer beads", "rosary", "religion", "necklace", "spiritual"],
        "💄": ["lipstick", "makeup", "red", "beauty", "cosmetic", "glamour"],
        "💍": ["ring", "diamond", "engagement", "marriage", "love", "jewelry"],
        "💎": ["gem", "diamond", "precious", "luxury", "sparkle", "jewel"],
        "🔇": ["muted", "silent", "no sound", "quiet", "speaker", "off"],
        "🔈": ["speaker low", "volume", "quiet", "sound", "audio", "soft"],
        "🔉": ["speaker medium", "volume", "sound", "audio", "medium"],
        "🔊": ["speaker high", "loud", "volume", "sound", "audio", "blast"],
        "📢": ["loudspeaker", "announce", "public", "broadcast", "megaphone"],
        "📣": ["megaphone", "announce", "loud", "shout", "cheer", "speaker"],
        "📯": ["postal horn", "bugle", "music", "announce", "ceremonial", "instrument"],
        "🔔": ["bell", "notification", "alert", "ring", "ding", "sound"],
        "🔕": ["bell slash", "silence", "no notification", "quiet", "off", "mute"],
        "🎼": ["musical score", "sheet music", "notes", "compose", "music", "staff"],
        "🎵": ["musical note", "music", "song", "tune", "audio", "note"],
        "🎶": ["musical notes", "music", "song", "melody", "audio", "harmony"],
        "🎙️": ["microphone", "podcast", "record", "speak", "broadcast", "voice"],
        "🎚️": ["level slider", "audio", "mix", "fader", "volume", "studio"],
        "🎛️": ["control knobs", "audio", "studio", "mix", "dial", "music"],
        "🎤": ["microphone", "sing", "karaoke", "speech", "performer", "stage"],
        "🎧": ["headphones", "music", "listen", "audio", "dj", "earphones"],
        "📻": ["radio", "broadcast", "fm", "am", "music", "news", "retro"],
        "🎷": ["saxophone", "jazz", "music", "instrument", "reed", "brass"],
        "🪗": ["accordion", "folk", "music", "instrument", "squeeze", "polka"],
        "🎸": ["guitar", "music", "rock", "string", "instrument", "electric", "strum"],
        "🎹": ["piano", "music", "keyboard", "classical", "instrument", "keys", "play"],
        "🎺": ["trumpet", "jazz", "music", "brass", "instrument", "fanfare", "blow"],
        "🎻": ["violin", "classical", "music", "string", "instrument", "fiddle", "bow"],
        "🪕": ["banjo", "country", "music", "string", "folk", "strum", "bluegrass"],
        "🥁": ["drum", "music", "beat", "rhythm", "percussion", "rock", "band"],
        "🪘": ["long drum", "music", "beat", "rhythm", "bass", "percussion", "djembe"],
        "📱": ["mobile phone", "smartphone", "iphone", "android", "call", "app", "text"],
        "📲": ["phone arrow", "incoming", "call", "mobile", "receive", "app"],
        "💻": ["laptop", "computer", "code", "tech", "macbook", "screen", "work"],
        "⌨️": ["keyboard", "type", "computer", "input", "qwerty", "keys", "desk"],
        "🖥️": ["desktop", "computer", "monitor", "screen", "mac", "work", "office"],
        "🖨️": ["printer", "paper", "print", "document", "office", "ink", "jet"],
        "🖱️": ["mouse", "computer", "click", "cursor", "pointer", "scroll", "input"],
        "🖲️": ["trackball", "input", "computer", "pointer", "cursor", "device"],
        "💽": ["minidisc", "storage", "data", "retro", "music", "disc", "old"],
        "💾": ["floppy disk", "save", "data", "storage", "retro", "old", "disk"],
        "💿": ["cd", "disc", "music", "data", "storage", "burn", "dvd", "shiny"],
        "📀": ["dvd", "disc", "movie", "data", "video", "storage", "shiny"],
        "🧮": ["abacus", "count", "math", "calculate", "ancient", "beads", "arithmetic"],
        "📷": ["camera", "photo", "picture", "snap", "shoot", "lens", "photography"],
        "📸": ["camera flash", "photo", "selfie", "picture", "snap", "flash"],
        "📹": ["video camera", "record", "film", "movie", "camera", "shoot"],
        "🎥": ["movie camera", "film", "record", "cinema", "shoot", "clapboard"],
        "📽️": ["film projector", "cinema", "movie", "retro", "reel", "theater"],
        "🎞️": ["film strip", "reel", "movie", "retro", "photo", "frames", "cinema"],
        "📞": ["telephone", "call", "old", "receiver", "talk", "ring", "handset"],
        "☎️": ["telephone", "call", "retro", "desk", "ring", "handset", "old"],
        "📟": ["pager", "beeper", "retro", "90s", "message", "device", "old"],
        "📠": ["fax", "machine", "office", "send", "retro", "document", "paper"],
        "📺": ["tv", "television", "watch", "show", "screen", "channel", "remote"],
        "🔋": ["battery", "charge", "power", "energy", "low", "electric", "juice"],
        "🪫": ["low battery", "empty", "dead", "charge", "power", "low"],
        "🔌": ["plug", "electric", "power", "outlet", "charge", "socket", "connect"],
        "💡": ["bulb", "idea", "light", "bright", "think", "inspiration", "tip"],
        "🔦": ["flashlight", "torch", "light", "dark", "beam", "camping"],
        "🕯️": ["candle", "flame", "light", "romantic", "glow", "wax", "dim"],
        "🪔": ["diya lamp", "india", "diwali", "flame", "oil", "light", "festival"],
        "🧯": ["extinguisher", "fire", "safety", "emergency", "red", "spray"],
        "🛢️": ["oil drum", "petroleum", "barrel", "fuel", "container", "industrial"],
        "💰": ["money bag", "cash", "rich", "dollar", "wealth", "bag", "gold"],
        "🪙": ["coin", "money", "gold", "silver", "currency", "round", "finance"],
        "💴": ["yen", "japan", "money", "currency", "note", "finance", "bank"],
        "💵": ["dollar", "money", "usa", "currency", "green", "bill", "cash"],
        "💶": ["euro", "europe", "money", "currency", "finance", "bill", "bank"],
        "💷": ["pound", "uk", "money", "currency", "britain", "sterling", "bill"],
        "💸": ["money wings", "spend", "cash", "fly", "expensive", "waste", "rich"],
        "💳": ["credit card", "pay", "bank", "swipe", "finance", "purchase", "tap"],
        "🪪": ["id card", "identity", "license", "wallet", "document", "personal"],
        "💹": ["chart increasing", "stock", "up", "money", "finance", "yen", "profit"],
        "📈": ["chart up", "increase", "stock", "growth", "profit", "bull", "rise"],
        "📉": ["chart down", "decrease", "loss", "stock", "drop", "bear", "fall"],
        "📊": ["bar chart", "data", "statistics", "graph", "analytics", "report"],
        "📋": ["clipboard", "list", "task", "copy", "paste", "document", "office"],
        "📌": ["pushpin", "pin", "location", "mark", "tack", "note", "important"],
        "📍": ["round pushpin", "location", "pin", "map", "place", "mark"],
        "📎": ["paperclip", "attach", "clip", "fasten", "office", "file", "connect"],
        "🖇️": ["linked paperclips", "connect", "together", "attach", "clip", "bind"],
        "📏": ["straight ruler", "measure", "length", "draw", "geometry", "school"],
        "📐": ["triangular ruler", "measure", "geometry", "angle", "draw", "school"],
        "✂️": ["scissors", "cut", "craft", "paper", "office", "snip", "trim"],
        "🗃️": ["card file box", "archive", "organize", "storage", "filing", "office"],
        "🗄️": ["file cabinet", "archive", "storage", "drawer", "office", "organize"],
        "🗑️": ["wastebasket", "trash", "delete", "garbage", "empty", "bin", "discard"],
        "🔒": ["lock", "secure", "private", "closed", "locked", "safe", "protect"],
        "🔓": ["unlock", "open", "access", "free", "unsecured", "open"],
        "🔏": ["lock pen", "private", "document", "sign", "sealed", "secure"],
        "🔐": ["lock key", "secure", "private", "login", "password", "credential"],
        "🔑": ["key", "unlock", "access", "door", "password", "secure", "login"],
        "🗝️": ["key", "old", "skeleton", "vintage", "lock", "door", "open"],
        "🔨": ["hammer", "build", "fix", "tool", "hit", "nail", "construct"],
        "🪓": ["axe", "chop", "wood", "lumberjack", "tool", "cut", "split"],
        "⛏️": ["pick", "mine", "dig", "tool", "mountain", "stone", "excavate"],
        "⚒️": ["hammer pick", "craft", "build", "mine", "tool", "smith"],
        "🛠️": ["tools", "wrench", "hammer", "fix", "build", "repair", "maintenance"],
        "🗡️": ["dagger", "sword", "stab", "weapon", "knife", "blade", "sharp"],
        "⚔️": ["swords", "fight", "battle", "combat", "cross", "weapon", "war"],
        "🛡️": ["shield", "protect", "defend", "guard", "armor", "security"],
        "🪚": ["carpentry saw", "wood", "cut", "tool", "build", "craft", "saw"],
        "🔧": ["wrench", "fix", "repair", "tool", "mechanical", "plumber", "adjust"],
        "🪛": ["screwdriver", "fix", "assemble", "tool", "screw", "repair", "build"],
        "🔩": ["bolt", "nut", "screw", "fix", "hardware", "fasten", "tool"],
        "⚙️": ["gear", "settings", "mechanical", "cog", "machine", "configure"],
        "🗜️": ["clamp", "compress", "tool", "vise", "squeeze", "hold", "fix"],
        "🔗": ["link", "chain", "url", "connect", "attach", "hyperlink", "web"],
        "⛓️": ["chains", "linked", "heavy", "restrain", "connect", "metal"],
        "🧲": ["magnet", "attract", "pull", "metal", "physics", "stick"],
        "🪜": ["ladder", "climb", "step", "up", "tall", "reach", "access"],
        "🔬": ["microscope", "science", "lab", "small", "research", "zoom", "biology"],
        "🔭": ["telescope", "space", "star", "observe", "astronomy", "far", "lens"],
        "📡": ["satellite dish", "signal", "communication", "receive", "broadcast", "space"],
        "💉": ["syringe", "injection", "vaccine", "medical", "needle", "shot", "health"],
        "🩸": ["drop of blood", "blood", "medical", "donate", "test", "health"],
        "💊": ["pill", "medicine", "drug", "health", "tablet", "capsule", "rx"],
        "🩹": ["bandage", "heal", "wound", "first aid", "cover", "injury", "fix"],
        "🩼": ["crutch", "injury", "heal", "support", "medical", "mobility", "walk"],
        "🩺": ["stethoscope", "doctor", "medical", "listen", "health", "diagnose"],
        "🩻": ["xray", "bone", "medical", "scan", "radiology", "skeleton", "health"],
        "🚪": ["door", "open", "close", "enter", "exit", "knock", "room"],
        "🛗": ["elevator", "lift", "floor", "up", "down", "building", "button"],
        "🪞": ["mirror", "reflect", "self", "vanity", "look", "image", "beauty"],
        "🪟": ["window", "view", "glass", "outside", "look", "room", "frame"],
        "🛏️": ["bed", "sleep", "rest", "bedroom", "night", "hotel", "cozy"],
        "🛋️": ["couch", "sofa", "sit", "relax", "lounge", "living room", "rest"],
        "🪑": ["chair", "sit", "seat", "furniture", "desk", "work", "office"],
        "🚽": ["toilet", "bathroom", "restroom", "wc", "loo", "flush", "throne"],
        "🪠": ["plunger", "unclog", "toilet", "fix", "plumber", "bathroom", "tool"],
        "🚿": ["shower", "bath", "clean", "wash", "hygiene", "rain", "refresh"],
        "🛁": ["bathtub", "bath", "soak", "relax", "clean", "hygiene", "bubbles"],
        "🪤": ["mousetrap", "trap", "catch", "mouse", "clever", "mechanism", "snap"],
        "🪣": ["bucket", "water", "carry", "clean", "mop", "container", "plastic"],
        "🧴": ["lotion bottle", "cream", "skin", "moisturizer", "pump", "care"],
        "🧷": ["safety pin", "fasten", "sew", "needle", "infant", "diaper", "attach"],
        "🧹": ["broom", "sweep", "clean", "witch", "halloween", "floor", "dust"],
        "🧺": ["basket", "laundry", "carry", "wicker", "hamper", "gather"],
        "🧻": ["roll of paper", "toilet", "tissue", "wipe", "bathroom", "kitchen"],
        "🧼": ["soap", "clean", "wash", "hygiene", "bubble", "lather", "sanitize"],
        "🪥": ["toothbrush", "dental", "clean", "teeth", "morning", "hygiene", "brush"],
        "🧽": ["sponge", "clean", "scrub", "wash", "absorb", "kitchen", "dish"],
        "🛒": ["shopping cart", "buy", "shop", "grocery", "store", "retail", "market"],
        "🚨": ["siren", "alert", "emergency", "police", "light", "alarm", "red"],
        "🚥": ["traffic light", "horizontal", "signal", "road", "stop", "go"],
        "🚦": ["traffic light", "vertical", "signal", "road", "stop", "go"],
        "🛑": ["stop sign", "halt", "no", "octagon", "traffic", "danger", "red"],
        "♻️": ["recycle", "environment", "green", "eco", "sustainability", "reuse"],
        "🔱": ["trident", "poseidon", "neptune", "symbol", "ocean", "three"],
        "📛": ["name badge", "label", "id", "identity", "hello", "tag"],
        "🔰": ["japanese symbol", "beginner", "green", "symbol", "novice", "learn"],
        "⭕": ["hollow red circle", "circle", "correct", "target", "zero", "o"],
        "✅": ["check", "done", "complete", "tick", "yes", "correct", "approve"],
        "☑️": ["ballot box check", "vote", "done", "check", "complete"],
        "✔️": ["checkmark", "done", "complete", "yes", "correct", "approve"],
        "❌": ["x", "no", "wrong", "error", "delete", "cross", "close", "cancel"],
        "❎": ["cross mark button", "no", "wrong", "cancel", "x", "false"],
        "🔴": ["red circle", "dot", "color", "stop", "alert", "red", "warning"],
        "🟠": ["orange circle", "dot", "color", "orange", "caution", "circle"],
        "🟡": ["yellow circle", "dot", "color", "caution", "warning", "sun"],
        "🟢": ["green circle", "dot", "go", "color", "correct", "positive", "success"],
        "🔵": ["blue circle", "dot", "color", "cool", "info", "circle"],
        "🟣": ["purple circle", "dot", "color", "royal", "lavender", "circle"],
        "⚫": ["black circle", "dark", "dot", "void", "empty", "circle"],
        "⚪": ["white circle", "light", "dot", "empty", "blank", "circle"],
        "🟤": ["brown circle", "dot", "earth", "warm", "color", "circle"],
        "🔺": ["red triangle up", "up", "warning", "point", "shape", "alert"],
        "🔻": ["red triangle down", "down", "warning", "shape", "point"],
        "💠": ["diamond blue", "shape", "gem", "crystal", "four point", "shiny"],
        "🔷": ["blue diamond", "shape", "large", "blue", "rhombus", "gem"],
        "🔹": ["blue diamond small", "shape", "small", "blue", "rhombus"],
        "🔶": ["orange diamond", "shape", "large", "orange", "rhombus", "warning"],
        "🔸": ["orange diamond small", "shape", "small", "orange", "rhombus"],
        "▪️": ["black small square", "shape", "dot", "black", "fill", "solid"],
        "▫️": ["white small square", "shape", "dot", "white", "empty", "outline"],
        "◾": ["black medium small square", "shape", "fill", "black", "solid"],
        "◽": ["white medium small square", "shape", "empty", "white", "outline"],
        "◼️": ["black medium square", "shape", "fill", "black", "solid"],
        "◻️": ["white medium square", "shape", "empty", "white", "outline"],
        "⬛": ["black large square", "shape", "solid", "black", "fill", "block"],
        "⬜": ["white large square", "shape", "empty", "white", "outline", "blank"],
        "🔲": ["black square button", "shape", "button", "solid", "black", "press"],
        "🔳": ["white square button", "shape", "button", "empty", "white", "press"],
        "❤️": ["heart", "love", "red", "romance", "passion", "care", "affection"],
        "🧡": ["orange heart", "love", "warm", "orange", "care", "affection"],
        "💛": ["yellow heart", "love", "friendship", "sunny", "bright", "care"],
        "💚": ["green heart", "love", "nature", "eco", "health", "envy", "fresh"],
        "💙": ["blue heart", "love", "calm", "trust", "sea", "sky", "deep"],
        "💜": ["purple heart", "love", "compassion", "royal", "military", "wounds"],
        "🖤": ["black heart", "dark", "love", "goth", "edgy", "rebel", "cool"],
        "🤍": ["white heart", "pure", "clean", "peace", "love", "innocent"],
        "🤎": ["brown heart", "earth", "warm", "love", "skin", "nature", "cozy"],
        "💔": ["broken heart", "sad", "heartbreak", "split", "loss", "pain", "end"],
        "❤️‍🔥": ["heart on fire", "passion", "intense", "burning", "love", "desire"],
        "❤️‍🩹": ["mending heart", "heal", "recover", "broken", "repair", "love"],
        "💕": ["two hearts", "love", "couple", "pair", "romance", "cute"],
        "💞": ["revolving hearts", "love", "spin", "romance", "affection", "care"],
        "💓": ["beating heart", "pulse", "love", "alive", "health", "thump"],
        "💗": ["growing heart", "love", "expand", "care", "pink", "affection"],
        "💖": ["sparkling heart", "love", "glitter", "special", "magic", "pink"],
        "💘": ["heart arrow", "cupid", "love", "valentine", "arrow", "shot"],
        "💝": ["heart ribbon", "gift", "love", "valentine", "box", "special"],
        "💟": ["heart decoration", "symbol", "ornament", "purple", "pattern"],
        "☮️": ["peace", "sign", "symbol", "dove", "hippie", "harmony", "love"],
        "✝️": ["cross", "christian", "religion", "church", "faith", "jesus"],
        "☦️": ["orthodox cross", "christian", "religion", "faith", "byzantine"],
        "🕉️": ["om", "hindu", "spiritual", "symbol", "meditation", "yoga"],
        "☸️": ["wheel of dharma", "buddhist", "dharma", "religion", "symbol", "spin"],
        "🪯": ["khanda", "sikh", "symbol", "religion", "spiritual", "punjab"],
        "✡️": ["star of david", "jewish", "symbol", "religion", "hexagram", "israel"],
        "🔯": ["dotted six pointed star", "hexagram", "symbol", "fortune", "mystical"],
        "🪬": ["hamsa", "protection", "symbol", "eye", "hand", "luck", "ward"],
        "☯️": ["yin yang", "balance", "taoist", "symbol", "duality", "harmony"],
        "🛐": ["place of worship", "religion", "pray", "kneel", "universal", "symbol"],
        "⛎": ["ophiuchus", "zodiac", "star sign", "13th", "astrological", "symbol"],
        "♈": ["aries", "zodiac", "ram", "march", "april", "star sign"],
        "♉": ["taurus", "zodiac", "bull", "april", "may", "star sign"],
        "♊": ["gemini", "zodiac", "twins", "may", "june", "star sign"],
        "♋": ["cancer", "zodiac", "crab", "june", "july", "star sign"],
        "♌": ["leo", "zodiac", "lion", "july", "august", "star sign"],
        "♍": ["virgo", "zodiac", "maiden", "august", "september", "star sign"],
        "♎": ["libra", "zodiac", "scales", "september", "october", "star sign"],
        "♏": ["scorpio", "zodiac", "scorpion", "october", "november", "star sign"],
        "♐": ["sagittarius", "zodiac", "archer", "november", "december", "star sign"],
        "♑": ["capricorn", "zodiac", "goat", "december", "january", "star sign"],
        "♒": ["aquarius", "zodiac", "water", "january", "february", "star sign"],
        "♓": ["pisces", "zodiac", "fish", "february", "march", "star sign"],
        "🆔": ["id", "identity", "symbol", "label", "personal", "button"],
        "⚕️": ["medical", "health", "symbol", "caduceus", "snake", "medicine"],
        "⚜️": ["fleur de lis", "france", "symbol", "heraldry", "lily", "royal"],
        "⛔": ["no entry", "forbidden", "stop", "banned", "do not", "restrict"],
        "🚫": ["prohibited", "banned", "no", "forbidden", "circle", "deny", "restrict"],
        "📵": ["no mobile", "banned", "silent", "off", "airplane", "restrict"],
        "🔞": ["no eighteen", "adult", "restricted", "age", "limit", "underage"],
        "💯": ["hundred", "perfect", "100", "score", "full", "all", "fire", "lit"],
        "🔀": ["shuffle", "random", "mix", "playlist", "order", "music"],
        "🔁": ["repeat", "loop", "again", "cycle", "continuous", "music"],
        "🔂": ["repeat one", "single", "loop", "one", "music", "song"],
        "▶️": ["play", "start", "begin", "music", "video", "go", "forward"],
        "⏩": ["fast forward", "skip", "quick", "speed", "double", "rush"],
        "⏭️": ["next track", "skip", "forward", "next", "song", "jump"],
        "⏯️": ["play pause", "toggle", "start", "stop", "media", "control"],
        "◀️": ["reverse", "back", "rewind", "previous", "left", "start"],
        "⏪": ["rewind", "back", "fast", "skip", "previous", "double"],
        "⏮️": ["previous track", "back", "start", "song", "rewind", "jump"],
        "🔼": ["up button", "increase", "volume", "arrow", "up", "raise"],
        "⏫": ["fast up", "double", "arrow", "up", "quick", "rise"],
        "🔽": ["down button", "decrease", "volume", "arrow", "down", "lower"],
        "⏬": ["fast down", "double", "arrow", "down", "quick", "drop"],
        "⏸️": ["pause", "stop", "wait", "hold", "break", "media", "freeze"],
        "⏹️": ["stop", "end", "halt", "square", "media", "finish", "cease"],
        "⏺️": ["record", "dot", "media", "capture", "circle", "red", "start"],
        "🎦": ["cinema", "movie", "film", "screen", "theater", "camera", "watch"],
        "🔅": ["low brightness", "dim", "dark", "screen", "reduce", "sun"],
        "🔆": ["high brightness", "bright", "screen", "sun", "light", "max"],
        "📶": ["signal", "bars", "wifi", "cellular", "strength", "network", "connection"],
        "🛜": ["wireless", "wifi", "internet", "signal", "network", "connect"],
        "📳": ["vibration mode", "phone", "silent", "buzz", "setting"],
        "📴": ["mobile off", "off", "silent", "airplane", "disable", "no signal"],
        "♀️": ["female", "woman", "gender", "sign", "symbol", "girl"],
        "♂️": ["male", "man", "gender", "sign", "symbol", "boy"],
        "⚧️": ["transgender", "gender", "symbol", "trans", "identity", "pride"],
        "✖️": ["multiply", "times", "math", "cross", "cancel", "x", "close"],
        "➕": ["plus", "add", "math", "more", "increase", "cross", "sum"],
        "➖": ["minus", "subtract", "math", "less", "decrease", "dash", "remove"],
        "➗": ["divide", "math", "split", "fraction", "percent", "ratio"],
        "🟰": ["equals", "same", "math", "balance", "fair", "neutral", "result"],
        "♾️": ["infinity", "forever", "loop", "eternal", "math", "limitless"],
        "‼️": ["double exclamation", "urgent", "shock", "emphasis", "warning", "alert"],
        "⁉️": ["exclamation question", "what", "huh", "surprise", "confused"],
        "❓": ["red question", "uncertain", "huh", "what", "query", "ask"],
        "❔": ["white question", "mild", "uncertain", "maybe", "ask", "query"],
        "❕": ["white exclamation", "alert", "mild", "note", "heads up"],
        "❗": ["red exclamation", "important", "urgent", "wow", "alert", "warning"],
        "〰️": ["wavy dash", "squiggle", "wave", "divider", "separator", "line"],
        "💱": ["currency exchange", "money", "exchange", "convert", "finance", "swap"],
        "💲": ["dollar sign", "money", "usd", "currency", "price", "pay"],
        "⚕": ["medical symbol", "caduceus", "health", "snake", "medicine", "rod"],
        "🔃": ["arrows clockwise", "refresh", "loop", "rotate", "cycle", "sync"],
        "🔄": ["arrows counterclockwise", "refresh", "sync", "cycle", "update", "loop"],
        "🔙": ["back", "arrow", "return", "previous", "go back", "left"],
        "🔚": ["end", "arrow", "last", "finish", "complete", "right"],
        "🔛": ["on", "switch", "enabled", "active", "running", "yes"],
        "🔜": ["soon", "coming", "near", "arrow", "forward", "upcoming"],
        "🔝": ["top", "arrow", "best", "first", "up", "highest", "raise"],
        "🛎️": ["bellhop bell", "hotel", "service", "ring", "call", "reception", "ping"],
        "🔢": ["input numbers", "123", "keypad", "number", "count", "digital"],
        "🔤": ["input latin", "abc", "letters", "type", "text", "keyboard", "alphabet"],
        "🅰️": ["blood type", "a", "medical", "red", "letter", "type"],
        "🅱️": ["blood type", "b", "medical", "red", "letter", "meme", "type"],
        "🆎": ["ab", "blood type", "medical", "combined", "type"],
        "🆑": ["cl", "symbol", "button", "clear", "clean"],
        "🆒": ["cool", "awesome", "great", "nice", "symbol", "button"],
        "🆓": ["free", "no cost", "gratis", "symbol", "button", "offer"],
        "🆕": ["new", "fresh", "novel", "recent", "symbol", "button"],
        "🆖": ["ng", "no good", "negative", "symbol", "button", "bad"],
        "🅾️": ["o", "blood type", "medical", "circle", "zero", "type"],
        "🆗": ["ok", "good", "agree", "fine", "symbol", "button", "correct"],
        "🅿️": ["p", "parking", "lot", "car", "sign", "blue", "letter"],
        "🆘": ["sos", "emergency", "help", "rescue", "distress", "signal", "danger"],
        "🆙": ["up", "level", "higher", "button", "symbol", "raise", "increase"],
        "🆚": ["vs", "versus", "compare", "against", "fight", "symbol", "battle"],
        "🈁": ["koko", "japanese", "here", "symbol", "katakana", "location"],
        "🈂️": ["sa", "japanese", "service", "symbol", "katakana", "charge"],
        "🈷️": ["moon", "japanese", "monthly", "symbol", "kanji", "amount"],
        "🈶": ["not free", "japanese", "occupied", "symbol", "kanji", "charge"],
        "🈯": ["reserved", "japanese", "symbol", "kanji", "pointing", "direct"],
        "🉐": ["bargain", "japanese", "discount", "symbol", "kanji", "deal"],
        "🈹": ["discount", "japanese", "sale", "symbol", "kanji", "reduce"],
        "🈚": ["free", "japanese", "no charge", "symbol", "kanji", "gratis"],
        "🈲": ["prohibited", "japanese", "banned", "symbol", "kanji", "forbidden"],
        "🉑": ["acceptable", "japanese", "symbol", "kanji", "ok", "allowed"],
        "🈸": ["apply", "japanese", "symbol", "kanji", "request", "submit"],
        "🈴": ["passing", "japanese", "grade", "symbol", "kanji", "meet"],
        "🈳": ["vacancy", "japanese", "empty", "symbol", "kanji", "available"],
        "🈵": ["no vacancy", "japanese", "full", "symbol", "kanji", "occupied"],
        "🏁": ["checkered flag", "race", "finish", "win", "formula1", "end", "speed"],
        "🚩": ["triangular flag", "mark", "alert", "point", "warning", "location"],
        "🎌": ["crossed flags", "japan", "celebration", "ceremony", "crossed"],
        "🏴": ["black flag", "pirate", "dark", "blank", "void"],
        "🏳️": ["white flag", "surrender", "peace", "truce", "blank"],
        "🏳️‍🌈": ["rainbow flag", "pride", "lgbtq", "rainbow", "gay", "inclusive"],
        "🏳️‍⚧️": ["transgender flag", "trans", "pride", "gender", "inclusive", "identity"],
        "🏴‍☠️": ["pirate flag", "skull", "crossbones", "jolly roger", "sea", "danger"],
        "⌚": ["watch", "time", "wrist", "clock", "hours", "smart", "apple"],
        "⏱️": ["stopwatch", "time", "race", "count", "second", "timer", "sport"],
        "⏲️": ["timer", "countdown", "alarm", "clock", "time", "minute", "second"],
        "⏰": ["alarm clock", "wake", "morning", "time", "ring", "reminder", "beep"],
        "🕰️": ["mantel clock", "vintage", "time", "retro", "hours", "old", "tick"],
        "⌛": ["hourglass", "time", "sand", "wait", "patience", "count", "done"],
        "⏳": ["hourglass flowing", "sand", "wait", "time", "process", "pending", "count"],
        "📁": ["file folder", "directory", "organize", "store", "computer", "folder"],
        "📂": ["open folder", "files", "directory", "expand", "navigate", "browse"],
        "🗂️": ["card index dividers", "organize", "tab", "sort", "office", "file", "divide"],
        "📅": ["calendar", "date", "schedule", "plan", "event", "month", "day"],
        "📆": ["tear off calendar", "calendar", "date", "day", "plan", "schedule", "month", "event"],
        "🗓️": ["spiral calendar", "calendar", "date", "plan", "schedule", "organizer", "event", "month"],
        "📇": ["card index", "contact", "business", "organize", "file", "info"],
        "🗒️": ["spiral notepad", "notes", "write", "memo", "draft", "list", "jot"],
        "📦": ["package", "box", "ship", "deliver", "parcel", "gift", "wrap"],
        "📬": ["mailbox open", "mail", "letter", "deliver", "receive", "post", "open"],
        "📫": ["mailbox closed", "mail", "letter", "empty", "post", "closed"],
        "📭": ["mailbox open no mail", "empty", "post", "receive", "open", "hollow"],
        "📮": ["postbox", "mail", "send", "post", "letter", "red", "drop"],
        "🗳️": ["ballot box", "vote", "election", "democracy", "choice", "poll"],
        "✏️": ["pencil", "write", "edit", "draw", "mark", "sketch", "yellow"],
        "✒️": ["black nib", "write", "ink", "sign", "pen", "calligraphy"],
        "🖋️": ["fountain pen", "write", "ink", "elegant", "sign", "formal", "classic"],
        "🖊️": ["pen", "write", "sign", "ink", "ballpoint", "click", "mark"],
        "🖌️": ["paintbrush", "art", "paint", "creative", "color", "brush", "stroke"],
        "🖍️": ["crayon", "draw", "color", "kid", "art", "wax", "creative"],
        "📝": ["memo", "write", "note", "draft", "document", "pencil", "compose"],
        "📖": ["open book", "read", "study", "learn", "story", "text", "chapter"],
        "📚": ["books", "library", "read", "study", "learn", "stack", "knowledge"],
        "📰": ["newspaper", "news", "media", "press", "article", "read", "daily"],
        "🗞️": ["rolled newspaper", "news", "press", "article", "roll", "journal", "read"],
        "📓": ["notebook", "write", "study", "lines", "school", "note", "journal"],
        "📔": ["notebook cover", "journal", "write", "diary", "study", "note", "pretty"],
        "📒": ["ledger", "account", "finance", "yellow", "book", "record", "log"],
        "📕": ["closed book", "red", "textbook", "read", "reference", "study"],
        "📗": ["green book", "read", "eco", "study", "reference", "text", "green"],
        "📘": ["blue book", "read", "study", "reference", "text", "academic", "blue"],
        "📙": ["orange book", "read", "study", "reference", "text", "warm", "orange"],
        "📜": ["scroll", "ancient", "document", "parchment", "decree", "old", "law"],
        "📄": ["page", "document", "file", "print", "write", "read", "text"],
        "📃": ["curled page", "document", "file", "sheet", "curl", "text", "print"],
        "📑": ["bookmark tabs", "index", "tab", "document", "organize", "divide", "page"],
        "🔖": ["bookmark", "save", "mark", "read", "page", "tag", "reminder"],
        "🏷️": ["label", "tag", "price", "sale", "mark", "identify", "sticker"],
        "🔍": ["search", "find", "look", "magnify", "zoom", "discover", "investigate"],
        "🔎": ["magnifying glass", "search", "find", "right", "zoom", "examine", "look"],
        "⭐": ["star", "favorite", "gold", "rate", "shine", "award", "night"],
        "🌟": ["glowing star", "shine", "gold", "special", "bright", "amazing", "wow"],
        "💫": ["dizzy", "star", "spin", "sparkle", "wow", "amazing", "hit"],
        "⚡": ["lightning", "zap", "electric", "fast", "bolt", "power", "storm", "energy"],
        "💥": ["boom", "explosion", "bang", "blast", "impact", "fire", "wow", "hit"],
        "🔥": ["fire", "hot", "lit", "flame", "burn", "heat", "trending", "spicy"],
        "🌙": ["crescent moon", "night", "moon", "sky", "sleep", "dark", "lunar"],
        "🌑": ["new moon", "dark", "moon", "phase", "night", "cycle", "black"],
        "🌒": ["waxing crescent", "moon", "phase", "night", "grow", "sky"],
        "🌓": ["first quarter moon", "half", "moon", "phase", "night", "sky"],
        "🌔": ["waxing gibbous", "moon", "phase", "night", "almost full", "sky"],
        "🌕": ["full moon", "moon", "bright", "night", "complete", "round", "sky"],
        "🌖": ["waning gibbous", "moon", "phase", "night", "sky", "decrease"],
        "🌗": ["last quarter moon", "half", "moon", "phase", "night", "wane", "sky"],
        "🌘": ["waning crescent", "moon", "phase", "night", "thin", "sky", "end"],
        "🌚": ["new moon face", "night", "dark", "moon", "creepy", "sneaky", "face"],
        "🌛": ["first quarter moon face", "moon", "sleepy", "night", "phase", "face"],
        "🌜": ["last quarter moon face", "moon", "night", "sleepy", "phase", "face"],
        "🌝": ["full moon face", "moon", "night", "bright", "face", "glow", "grin"],
        "🌞": ["sun face", "sunny", "warm", "happy", "bright", "day", "smile"],
        "🪐": ["ringed planet", "saturn", "space", "orbit", "ring", "planet", "solar"],
        "☄️": ["comet", "meteor", "space", "streak", "fast", "fire", "sky", "night"],
        "🦫": ["Kanta"]
        
    ]

    private init() {
        self.allEmojis = loadAndMerge()
        loadJapanese()
    }

    // MARK: - Japanese Data Loading

    private struct JaEntry {
        let shortName: String
        let keywords:  [String]

        /// Returns true if the query (already lowercased) matches this entry.
        func matches(_ query: String) -> Bool {
            shortName.contains(query) || keywords.contains { $0.contains(query) }
        }

        /// Higher score = better match quality.
        func score(for query: String) -> Int {
            if shortName == query                                    { return 4 }
            if shortName.hasPrefix(query)                           { return 3 }
            if keywords.contains(where: { $0 == query })            { return 2 }
            if keywords.contains(where: { $0.hasPrefix(query) })    { return 1 }
            return 0
        }
    }

    private func loadJapanese() {
        guard
            let url  = Bundle.main.url(forResource: "emoji_ja", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let dict = try? JSONSerialization.jsonObject(with: data) as? [String: [String: Any]]
        else { return }

        for (key, info) in dict {
            let shortName = info["short_name"] as? String ?? ""
            let keywords  = info["keywords"]   as? [String] ?? []
            jaLookup[key] = JaEntry(shortName: shortName, keywords: keywords)
        }
    }

    // MARK: - Language Detection

    /// True when the query contains at least one hiragana, katakana, or CJK character.
    /// Works regardless of the Mac's system language setting.
    private func isJapanese(_ text: String) -> Bool {
        text.unicodeScalars.contains {
            (0x3040...0x309F).contains($0.value) ||   // Hiragana
            (0x30A0...0x30FF).contains($0.value) ||   // Katakana
            (0x4E00...0x9FFF).contains($0.value) ||   // CJK Unified Ideographs
            (0x3400...0x4DBF).contains($0.value)      // CJK Extension A
        }
    }

    private func loadAndMerge() -> [EmojiEntry] {
    // 1. Load both files
    let master = loadJSON(named: "unicode_master")
    let github = loadJSON(named: "github_emojis")
        
    // 2. Create a lookup for GitHub data (emoji character is the key)
    let githubLookup = Dictionary(uniqueKeysWithValues: github.map { ($0.emoji, $0) })
        
    // 3. Merge
    return master.map { official in
        var finalAliases = Set<String>()
        var finalTags = Set<String>()
            
        // Add words from the official description as tags
        official.description.lowercased()
            .components(separatedBy: " ")
            .filter { $0.count > 2 }
            .forEach { finalTags.insert($0) }

        // Layer in GitHub aliases/tags if they exist
        if let smartData = githubLookup[official.emoji] {
            smartData.aliases.forEach { finalAliases.insert($0) }
            smartData.tags.forEach { finalTags.insert($0) }
        }
            
        // Layer in Tier 3: Your Hand-Built Overrides
        if let custom = handBuiltAliases[official.emoji] {
            custom.forEach { finalAliases.insert($0) }
        }
            
        return EmojiEntry(
            emoji: official.emoji,
            description: official.description,
            aliases: Array(finalAliases),
            tags: Array(finalTags)
        )
        }
    }
    
    private func loadJSON(named name: String) -> [EmojiEntry] {
        guard let url = Bundle.main.url(forResource: name, withExtension: "json"),
                let data = try? Data(contentsOf: url),
                let list = try? JSONDecoder().decode([EmojiEntry].self, from: data) else {
            return []
        }
        return list
    }
    
    // MARK: - Frequency Tracking & Search Engine

    var frequencies: [String: Int] {
        get { (UserDefaults.standard.dictionary(forKey: frequencyKey) as? [String: Int]) ?? [:] }
        set { UserDefaults.standard.set(newValue, forKey: frequencyKey) }
    }

    // MARK: - Custom Keywords
    // Maps a user-defined keyword (lowercased) → emoji character.
    // Any emoji whose custom keyword matches the query is always ranked first (score 999).

    var customKeywords: [String: String] {
        get {
            (UserDefaults.standard.dictionary(forKey: customKeywordsKey) as? [String: String]) ?? [:]
        }
        set {
            UserDefaults.standard.set(newValue, forKey: customKeywordsKey)
            objectWillChange.send()
        }
    }

    func addCustomKeyword(_ keyword: String, for emoji: String) {
        guard !keyword.trimmingCharacters(in: .whitespaces).isEmpty else { return }
        var kw = customKeywords
        kw[keyword.lowercased().trimmingCharacters(in: .whitespaces)] = emoji
        customKeywords = kw
    }

    func removeCustomKeyword(_ keyword: String) {
        var kw = customKeywords
        kw.removeValue(forKey: keyword.lowercased())
        customKeywords = kw
    }

    /// Returns the custom-keyword score (999 if match, 0 otherwise).
    private func customKeywordScore(for query: String, emoji: String) -> Int {
        let kw = customKeywords
        let matches = kw.contains { (keyword, targetEmoji) in
            targetEmoji == emoji && keyword.hasPrefix(query)
        }
        return matches ? 999 : 0
    }

    func recordUsage(of emoji: String) {
        var f = frequencies
        f[emoji, default: 0] += 1
        frequencies = f
    }

    func search(query: String) -> [EmojiEntry] {
        guard !query.isEmpty else { return [] }
        let f = frequencies

        return isJapanese(query)
            ? searchJapanese(query: query, frequencies: f)
            : searchEnglish(query: query, frequencies: f)
    }

    // MARK: - English Search Path

    private func searchEnglish(query: String, frequencies f: [String: Int]) -> [EmojiEntry] {
        let q = query.lowercased()

        return allEmojis
            .filter { entry in
                // Custom keyword match always includes the emoji
                customKeywordScore(for: q, emoji: entry.emoji) > 0
                    || entry.matches(query: q)
            }
            .sorted { a, b in
                // 1. Custom keyword — always first
                let ckA = customKeywordScore(for: q, emoji: a.emoji)
                let ckB = customKeywordScore(for: q, emoji: b.emoji)
                if ckA != ckB { return ckA > ckB }

                // 2. Usage frequency
                let fA = f[a.emoji, default: 0], fB = f[b.emoji, default: 0]
                if fA != fB { return fA > fB }

                // 3. Match quality
                let sA = a.bestMatchScore(for: q, isHandBuilt: handBuiltAliases[a.emoji] != nil)
                let sB = b.bestMatchScore(for: q, isHandBuilt: handBuiltAliases[b.emoji] != nil)
                if sA != sB { return sA > sB }

                return a.emoji < b.emoji
            }
            .prefix(15).map { $0 }
    }

    // MARK: - Japanese Search Path
    // Triggered when the query contains hiragana, katakana, or kanji.
    // Uses emoji_ja.json (CLDR Japanese) + jaHandBuiltAliases (internet slang).
    // Custom keywords also work in this path.

    private func searchJapanese(query: String, frequencies f: [String: Int]) -> [EmojiEntry] {
        return allEmojis
            .filter { entry in
                // Always include custom-keyword matches
                if customKeywordScore(for: query, emoji: entry.emoji) > 0 { return true }

                // CLDR Japanese data
                if let ja = jaLookup[entry.emoji], ja.matches(query) { return true }

                // Hand-built Japanese aliases
                if let extras = jaHandBuiltAliases[entry.emoji],
                   extras.contains(where: { $0.contains(query) }) { return true }

                return false
            }
            .sorted { a, b in
                // 1. Custom keyword — always first
                let ckA = customKeywordScore(for: query, emoji: a.emoji)
                let ckB = customKeywordScore(for: query, emoji: b.emoji)
                if ckA != ckB { return ckA > ckB }

                // 2. Usage frequency
                let fA = f[a.emoji, default: 0], fB = f[b.emoji, default: 0]
                if fA != fB { return fA > fB }

                // 3. Japanese match quality
                let sA = japaneseScore(for: query, emoji: a.emoji)
                let sB = japaneseScore(for: query, emoji: b.emoji)
                if sA != sB { return sA > sB }

                return a.emoji < b.emoji
            }
            .prefix(15).map { $0 }
    }

    /// Combined Japanese score: CLDR data + hand-built aliases.
    private func japaneseScore(for query: String, emoji: String) -> Int {
        var score = 0

        // Bonus from CLDR data
        if let ja = jaLookup[emoji] { score = max(score, ja.score(for: query)) }

        // Bonus from hand-built aliases
        if let extras = jaHandBuiltAliases[emoji] {
            if extras.contains(query)                          { score = max(score, 4) }
            else if extras.contains(where: { $0.hasPrefix(query) }) { score = max(score, 3) }
            else if extras.contains(where: { $0.contains(query) })  { score = max(score, 1) }
        }

        return score
    }
}
